### ISSUE TITLE
Support local Lambda invocations using the FunctionName

### ISSUE THREAD

**Issue by kylevoyto** [awslabs/aws-sam-cli#1025]
### Proposal

Support local Lambda invocations based on the FunctionName in addition to the Logical ID.

### Issue

The following Lambda function is defined in my SAM template:

```
Resources:
  MainFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: org-project-main
      CodeUri: functions/main/
      Handler: main.lambda_handler
      Timeout: 15
```

I want to invoke the Lambda function locally using the name defined in the FunctionName property:

```
sam local invoke "org-project-main" --no-event
```

But the error is produced:

```
2019-02-25 13:25:19 org-project-main not found. Possible options in your template: ['MainFunction', 'OtherFunction']
Error: Function org-project-main not found in template
```

We follow the convention at my institution to name Lambda functions like org-project-name, which is allowed by Lambda, but the Logical ID of the resource (MainFunction in this case) must be alphanumeric. Therefore, I cannot set the Logical ID and the FunctionName to the same value.

### Additional Details

I am using `sam --version`:

```
SAM CLI, version 0.11.0
```

On macOS `sw_vers`:

```
ProductName:    Mac OS X
ProductVersion: 10.14.3
BuildVersion:   18D109
```
