### ISSUE TITLE
Unable to set CORS headers when there is a unhandled Lambda exception

### ISSUE THREAD

**Issue by talawahtech** [awslabs/aws-sam-cli#1027]
### Description
If I create a `AWS::Serverless::Function` that is triggered by an API Gateway event, and an unhandled exception occurs in my code, the error message sent back to the user is a 502 Bad Gateway error from the API Gateway. Unfortunately this error message doesn't have any CORS headers by default, so if the webpage that called the endpoint is not on the same domain as the API Gateway, a CORS error will also be triggered in the browser.

Previously when I used the [serverless framework](https://serverless.com/) I would address this issue by creating a CloudFormation resource to set the `DEFAULT_5XX` Gateway Response for that particular API. For some reason doing so doesn't seem to have any effect for APIs created using sam-cli.

### Steps to reproduce
1) Create a `AWS::Serverless::Function` with an event of type `Api` and throw an exception when the function is called.

2) Add the following resource to template.yaml
```
  GatewayResponseDefault5XX:
    Type: 'AWS::ApiGateway::GatewayResponse'
    Properties:
      ResponseParameters:
        gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
        gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
      ResponseType: DEFAULT_5XX
      RestApiId: !Ref ServerlessRestApi
```
### Observed result
No CORS headers are present on the 502 response from the API endpoint

### Expected result
CORS headers *should be* present on the 502 response from the API endpoint

I am not sure if this has something to do with the fact that sam-cli uses embedded swagger templates when defining the RestApi, but that would be my first guess. I am just looking for a way to address the issue, even if it is another workaround
