### ISSUE TITLE
Feature: codeBuild test integration

### ISSUE THREAD

**Issue by P00L** [awslabs/aws-sam-cli#1041]
This days I'm trying to integrate unit and integration test into codeBuilt within a codePipeline using sam local commands, but I'm having some troubles. Would be great to have a reference example of integration of sam with codebuild for test.
Thanks

**Comment by jfuss** [comment]
@P00L Can you be more descriptive of the troubles you are running into? You should be able to install SAM CLI into the CodeBuild image and use the commands you need too. Not 100% sure if CodeBuild support Docker, which would be needed if you wanted to invoke the function in your CI/CD. But at that point, my recommendation is to deploy the function to a test environment and run the automated tests on the service. This would get you complete confidence that what you are deploying works on the same system your service runs on instead of a local implementation that could have deviations.

**Comment by orozcoadrian** [comment]
I'm currently migrating my CodeBuild buildspecs to use SAM. The roadblocks I ran into was having to leave the `--template-file` out of the `sam package` command as well as figuring out how to install and configure `sam`. Note that I'm not running integration tests (no use of sam local). I'm only running unit tests and I do that by letting `sam` build my gradle project. Here's my setup, in case it helps:

#### CodeBuild:
Image: aws/codebuild/java:openjdk-8-1.6.0
Environment type: Linux

#### buildspec:
```
version: 0.2

phases:
  install:
    commands:
      - lsb_release -a # output OS name and version
      - pip install --user --upgrade awscli # https://github.com/pierreis/sam-codebuild-starter/blob/master/buildspec.yml
      - pip install --user --upgrade aws-sam-cli
      - USER_BASE_PATH=$(python -m site --user-base) # https://github.com/awslabs/aws-sam-cli/issues/349
      - export PATH=$PATH:$USER_BASE_PATH/bin
  build:
    commands:
      - sam build --template myTemplate.yml
      - |
        sam package \
        --s3-bucket myBucket \
        --output-template-file myPackagedTemplate.yml
artifacts:
  type: zip
  files:
    - myPackagedTemplate.yml
cache:
  paths:
    - '/root/.gradle/wrapper/**/*'
```
