### ISSUE TITLE
Cannot reference existing bucket as event source

### ISSUE THREAD

**Issue by dpolicastro** [awslabs/aws-sam-cli#1061]
### Description
I'm trying to deploy some functions that uses an existing bucket as a reference, but I've read that is not possible, every time I want to use a bucket as an event source CF have to create a new one. 

### Steps to reproduce
```
Resources:
  DownloadFile:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: download-file
      Role: arn:aws:iam::my-role
      Handler: app.download_file
      Events:
        S3Trigger:
          Type: S3
          Properties:
            Bucket:
              Ref: MyBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                - Name: prefix
                  Value: entry/
  MyBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-bucket
```
### Observed result

Please provide command output with `--debug` flag set.

16:44:21 UTC-0300 | CREATE_FAILED | AWS::S3::Bucket | MyBucket | my-bucket already exists
-- | -- | -- | -- | --

### Expected result

I was expecting that CloudFormation identified the existing resource and used it instead of trying to create one.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Ubuntu 18.04
2. `sam --version`: 0.13.0

`Add --debug flag to command you are running`
