### ISSUE TITLE
sam publish succeeds, but new SemanticVersion not found when building parent stack

### ISSUE THREAD

**Issue by ericallam** [awslabs/aws-sam-cli#1065]
### Description

After using `sam publish` to publish a new SemanticVersion of an existing public serverless repo application successfully, subsequently attempting to use `sam build` on a parent stack with the new `SemanticVersion` specified in the `AWS::Serverless::Application` results in an exception. 

For example, I updated [arn:aws:serverlessrepo:us-east-1:958845080241:applications/lambda-logs-event-source](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:958845080241:applications~lambda-logs-event-source) to SemanticVersion `1.0.2` using `sam publish`, which is correctly reflect in the AWS Console:

<img width="937" alt="Screenshot 2019-03-19 at 11 48 28" src="https://user-images.githubusercontent.com/534/54603722-f6c35380-4a3c-11e9-8e3a-571f4d7004f8.png">

I then attempted to build [this SAM app](https://github.com/solve-hq/ship-logs-to-honeycomb) which includes this `Serverless::Application` resource definition:

```yaml
  LogSource:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:958845080241:applications/lambda-logs-event-source
        SemanticVersion: 1.0.2
      Parameters:
        EventProcessorFunctionName: !Ref ShipLogsToHoney
```

Which results in an error. Weirdly, when attempting to deploy the serverless application from the AWS Console using the "Deploy" button the public profile page, the version is correctly displayed:

<img width="1135" alt="Screenshot 2019-03-19 at 11 27 45" src="https://user-images.githubusercontent.com/534/54603912-6c2f2400-4a3d-11e9-8dc8-3adc91684659.png">

Attempting to retrieve the list of versions of the application using the aws cli fails to display anything other than the initial version:

```bash
$  aws serverlessrepo list-application-versions --application-id arn:aws:serverlessrepo:us-east-1:958845080241:applications/lambda-logs-event-source
{
    "Versions": [
        {
            "ApplicationId": "arn:aws:serverlessrepo:us-east-1:958845080241:applications/lambda-logs-event-source",
            "CreationTime": "2019-03-08T16:50:55.197Z",
            "SemanticVersion": "1.0.0",
            "SourceCodeUrl": "https://github.com/solve-hq/lambda-logs-event-source"
        }
    ]
}
```

### Steps to reproduce

1. Clone parent application: https://github.com/solve-hq/ship-logs-to-honeycomb
2. Run `sam build`

### Observed result

https://gist.github.com/ericallam/fc719b79e8d300a790c3dd74e97c854d

### Expected result

`sam build` should be able to find the new SemanticVersion

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: macOS Mojave 10.14
2. `sam --version`: SAM CLI, version 0.13.0
