### ISSUE TITLE
sam validate breaks when using Auth block under AWS::Serverless::Api

### ISSUE THREAD

**Issue by terlar** [awslabs/aws-sam-cli#1074]
### Description

When having a `template.yaml` including an `Auth` property under `AWS::Serverless::Api` it is invalid with a very confusing error message. If I remove this configuration the `sam validate` command validates properly.

### Steps to reproduce

A `template.yaml` including:
```
  ...
  BaseApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        DefaultAuthorizer: MyAuthorizer
        Authorizers:
          MyAuthorizer:
            FunctionArn: !GetAtt MyAuthFunction.Arn
            Identity:
              Header: Authorization
              ValidationExpression: Bearer .*
              ReauthorizeEvery: 299 # Seconds

  MyAuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/
      Handler: myAuthorizer.handler
  ...
```

### Observed result

I skipped the `--debug` flag as it might include some sensitive information and I didn't see any valuable output there.

With `Auth` config:
```
$ sam validate
Template provided at '/var/opt/template.yaml' was invalid SAM Template.
Error:  
```

Without `Auth` config:
```
$ sam validate
/var/opt/template.yaml is a valid SAM Template
```

### Expected result

The template would be valid even with an Auth section defined.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Linux
2. `sam --version`: 0.13.0
