### ISSUE TITLE
No log file is written with --log-file or -l

### ISSUE THREAD

**Issue by sthware** [awslabs/aws-sam-cli#124]
When I run start-api using this command (or variants):

`sam local start-api --log-file ./out.log`

Variants tried:

`sam local start-api --log-file=./out.log`
`sam local start-api --log-file out.log`
`sam local start-api --log-file=out.log`
`sam local start-api -l ./out.log`

no output file is written (nor created), and no error message is displayed.
My handler's return value is displayed in the console as expected.

template.yaml:

```
AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: My first serverless application.

Resources:

  Products:
    Type: AWS::Serverless::Function
    Properties:
      Handler: products.handler
      Runtime: python3.6
      FunctionName: products_handler
      CodeUri: ./dist
      Events:
        ListProducts:
          Type: Api
          Properties:
            Path: /products
            Method: get
        Product:
          Type: Api
          Properties:
            Path: /products/{product}
            Method: any
```

Test case:

```
import logging
LOGGER = logging.getLogger(__name__)
LOGGER.setLevel(logging.INFO)

def handler(event, context):
  LOGGER.error("Test message")
  return {'body': "some output\n"}
```

Command:

`curl http://localhost:3000/products`

If I set my logger to log to stdout/stderr (using logging.StreamHandler), I do see log message on the console,
but not using the aforementioned method (nor using any file-based ones, either, which I wouldn't expect to work anyway.)

Everything else works.

What am I missing?
