### ISSUE TITLE
Random account number in arn

### ISSUE THREAD

**Issue by adubkov** [awslabs/aws-sam-cli#1245]
Hi,

When I'm running: 
```
sam local start-api
```
and then call my function with
```
curl -v http://127.0.0.1:3000/
```
 Function arn gets random account number:
```
# first call
arn:aws:lambda:us-west-2:248916186:function:test
# second call
arn:aws:lambda:us-west-2:62267986:function:test
# third call
arn:aws:lambda:us-west-2:1375389276:function:test
```
 Is there a way to make it static and is there a way to change function name and region?

**Comment by adubkov** [comment]
I found this, which works for me:
```yaml
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          AWS_LAMBDA_FUNCTION_INVOKED_ARN: "arn:aws:lambda:ap-south-1:111111111:function:foo"
```
