### ISSUE TITLE
Transform AWS::Server less-2016-10-31 failed 

### ISSUE THREAD

**Issue by azarboon** [awslabs/aws-sam-cli#1317]
We have Windows 7 workstations. I successfully installed AWS SAM on my machine and developed our application. My SAM cli  version is 0.16.1. I don't remember which method I took to install it on my Windows.

Now my colleague is trying to install SAM and work on the application but he can't get it working. He has docker v18.09.3 installed, installed SAM MSI file. His SAM cli version is 0.18.0 but he can't deploy our application and he gets this error (same template works on my machine):

> "Failed to create the changeset: Waiter ChangeSetCreateComplete failed: Waiter en
> countered a terminal failure state Status: FAILED. Reason: Transform AWS::Server
> less-2016-10-31 failed with: Invalid Serverless Application Specification docume
> nt. Number of errors found: 1. Resource with id [id] is invalid.
> 'ContentUri' is not a valid S3 Uri of the form "s3://bucket/key" with optional v
> ersionId query parameter."

The error is referring to this resource in our template:

```
  MyLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: MyLayer
      ContentUri: ./Layer
      CompatibleRuntimes:
        - nodejs10.x
      RetentionPolicy: Retain          

```

I contacted AWS support about this and they mentioned that this is a bug. They recommended me to update all dependencies (awscli, boto3 and botocore). Even though we installed AWS CLI and SAM cli via MSI file, still upgraded dependencies through pip:

```
pip3 list
boto3: 1.19.197
botocore 1.12.197
aws –version:
aws-cli/1.16.2019 Python/3.6.0 Windows/7 botocore/1.12.199
sam --version
SAM CLI version 0.18.0
python –version
3.7.4
pip3 –version
19.0.3
```

And still the issue persists. AWS Support again confirmed the bug and they said they are investigating it. I'm posting it here to hopefully speed up the process and to help others who may have same issue.
