### ISSUE TITLE
Unable to import from root folder

### ISSUE THREAD

**Issue by MatteoGioioso** [awslabs/aws-sam-cli#1339]
I have all my functions in the root folder where the `template.yaml` is located

```
MyFunction.js
MyFunction2.js
MyFunction3.js
template.yaml
```

Then in my template I have the following code

```
MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: MyFunction
      CodeUri: ./MyFunction
      Handler: MyFunction.handler
      Runtime: nodejs8.10
     ...
```
And my function code
```
exports.handler = async () => {
  return {status: 200, {message: 'Ok'}}
};

```
But when I test the function with `sam local start-api`
I get this error: 

```
Unable to import module 'MyFunction': Error
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)

```

if I try to reference this way `CodeUri: ./MyFunction.js`
it give me this other error

```
("OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"rootfs_linux.go:58: mounting 
```
But I guess Docker has to mount a directory

**Comment by jfuss** [comment]
@MatteoGioioso If all your functions are in the root then the `CodeUri` should either be `.` or removed. We will default to `CodeUri: .` if the property is not specified. CodeUri is the directory of where the handler is located (aka your function). It looks like you are specifying it as the `.js` file instead.

**Comment by MatteoGioioso** [comment]
@jfuss Thanks, I have literally tried all options available but not the one you suggested, which works. However I have discovered that with this folder structure I have achieved nothing. I though that instead of having a single `index.js` file with all the functions there, I could split them into single files to decrease bundle size. Well unfortunately nothing changed, same bundle size for all the functions.

**Comment by jfuss** [comment]
@MatteoGioioso If you are trying to have singular functions, you where on the right track. Take a look at how our init's are structured (`sam init --runtime nodejs10.x`). This will show you how we recommend setting up functions. 

Short example:

Directory structure
```
- function1
  - MyFunction.js
  - package.json
- function2
  - MyFunction2.js
  - package.json
- template.yaml
```

template.yaml
```
MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: MyFunction
      CodeUri: ./function1
      Handler: MyFunction.handler
      Runtime: nodejs8.10
     ...
MyFunction2:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: MyFunction2
      CodeUri: ./function2
      Handler: MyFunction2.handler
      Runtime: nodejs8.10
     ...
```

Each function gets their own directories (and package.json if you are using `sam build`). Then during package only that directory will be zipped and associated with the function, creating minimal deployment packages for each function. Saying `CodeUri: .` tells package to zip of that whole directory, which will include everything (most of the time that isn't what you want unless its a super simple app).

Hope that helps and shows what I think you are after is possible.
