### ISSUE TITLE
Template format error: Every Default member must be a string

### ISSUE THREAD

**Issue by MatteoGioioso** [awslabs/aws-sam-cli#1358]
### Description
I am trying to add environmental variables to my deploying script from an external file, but I keep getting this error

```
An error occurred (ValidationError) when calling the CreateChangeSet operation: Template format error: Every Default member must be a string
```

### Steps to reproduce

This is my deploying script

```
sam deploy \
    --template-file output.yaml \
    --stack-name someStackName \
    --capabilities CAPABILITY_IAM \
    --parameter-overrides \
        Environment=$ENV  \
        $(jq -r '.[] | [.ParameterKey, .ParameterValue] | join("=")' production.json)
```
And this is my `production.json`
```
[
  {
    "ParameterKey": "DynamoDbUrl",
    "ParameterValue": "https://someDynamoDbUrl"
  },
  {
    "ParameterKey": "MySecretKey",
    "ParameterValue": "someSecretKey"
   }
  ....
]

```

And in my `template.yaml` I have declared all the parameters

```
Parameters:
  Environment:
    Type: String
AwsRegion:
    Type: String
    Default: !Sub ${AWS::Region}
StateMachineArn:
    Type: String
    Default: !GetAtt [grabRepositoryProcess, Arn]
  DynamoDbUrl:
    Type: String
  MySecretKeu:
    Type: String
```

### Observed result

This is the relevant line:
```
returned non-zero exit status 255
./deploy.sh: line 24: DynamoDbUrl=https://someDynamoDbUrl: No such file or directory
```

### Expected result

No error

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Ubuntu 18.04.3 LTS 
2. `sam --version`: 0.18.0

`Add --debug flag to command you are running`
