### ISSUE TITLE
"URL cannot include query-string parameters (after '?')" error

### ISSUE THREAD

**Issue by khamaileon** [awslabs/aws-sam-cli#1401]
### Description

I'm trying to host a Python/Django project on AWS Lambda. But when I connect to Django's admin, I get a 403 error:

`Content-Type:application/x-www-form-urlencoded, URL cannot include query-string parameters (after '?'): '/admin/login/?next=/admin/'`

NB: I did't have this problem with the Serverless framework

### Request content

POST https://domain.tld/admin/login/?next=/admin/

***Request headers***
```
Host: domain.tld
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Content-Type: application/x-www-form-urlencoded
Content-Length: 138
Connection: keep-alive
Referer: https://domain.tld/admin/login/?next=/admin/
Cookie: csrftoken=A5r8Xxnv0x6EWHOYJEq3zZvMyGCoRWU5ozSfOXaArmWwD4LYFHuYEsStt4Bb9ugB
Upgrade-Insecure-Requests: 1
TE: Trailers
```

***Response headers***
```
HTTP/2.0 403 Forbidden
content-type: application/json
content-length: 155
date: Thu, 05 Sep 2019 14:32:22 GMT
x-amzn-requestid: 05341664-1cc7-4cc6-951d-8f229820d86b
x-amzn-errortype: IncompleteSignatureException
x-amz-apigw-id: fjFicHuZjoEFg3Q=
x-cache: Error from cloudfront
via: 1.1 xxx.cloudfront.net (CloudFront)
x-amz-cf-pop: CDG3-C2
x-amz-cf-id: Xdkmr_gSedl-l2jbkh-dlj8dJzR8ZwxPnkd2n49KWALfRboG5sJbMA==
X-Firefox-Spdy: h2
```

***Response payload***
```json
{"message":"When Content-Type:application/x-www-form-urlencoded, URL cannot include query-string parameters (after '?'): '/admin/login/?next=/admin/'"}
```

### Code

**app.py**
```python
import awsgi

from .wsgi import application

def lambda_handler(event, context):
    return awsgi.response(application, event, context)
```

**template.yaml**
```yaml
---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: My project stack

Parameters:
  AwsLocation:
    Type: String

  DatabaseUrl:
    Type: String

Globals:
  Function:
    Timeout: 10
    Runtime: python3.6

Resources:
  SuggestionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: project.app.lambda_handler
      Policies:
        - VPCAccessPolicy: {}

      VpcConfig:
        SecurityGroupIds:
          - xxx
        SubnetIds:
          - xxx
          - xxx
          - xxx

      Events:
        Base:
          Type: Api
          Properties:
            Path: /
            Method: get

        Proxy:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: get

      Environment:
        Variables:
          AWS_LOCATION: !Ref AwsLocation
          DATABASE_URL: !Ref DatabaseUrl

Outputs:
  EndpointUrl:
    Description: API Gateway endpoint URL
    Value: !Sub https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/

```

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

- Ubuntu 18.04
- SAM CLI, version 0.21.0
- Python 3.6.8
- Django 2.2.4
- [AWSGI](https://github.com/slank/awsgi) as WSGI adapter for AWS API Gateway/Lambda Proxy Integration

**Comment by awood45** [comment]
Are you getting this error on AWS Lambda itself, testing locally, or both? It reads like this is after a deployment, but want to be sure.

**Comment by khamaileon** [comment]
@awood45 on AWS Lambda itself

**Comment by khamaileon** [comment]
I solved this by switching my API resource from GET to ANY.
```yaml
      Events:
        Base:
          Type: Api
          Properties:
            Path: /
            Method: any

        Proxy:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
```
