### ISSUE TITLE
Scheduled lambda failed to trigger

### ISSUE THREAD

**Issue by antoniuslin** [awslabs/aws-sam-cli#1433]
Hello,

I'm not sure if this is a true issue or a feature request or more of a PEBCAK. I have the following lambda definition in my SAM's `template.yaml`

```
    TestScheduledFunction:
      Type: AWS::Serverless::Function
      Properties:
        Handler: app.test
        Events:
          Promech:
            Type: Api
            Properties:
              Schedule: rate(1 minute)
              Path: /test
              Method: any
```

The function content is a simple `js` function in `app.js`:

```javascript
exports.test = async(event, context, callback) => {
  console.log('triggered call @:', (new Date()).toISOString());
}
```

I'm able to call the lambda just fine via standard `curl` call like so:

```bash
$> curl http://localhost:3000/test
```

as well as using local invocation like so:

```bash
$> sam local invoke TestScheduledFunction --no-event
```

both resulting in similar server-side output like so (with the respective differences):

```
START RequestId: b3ed7724-be8d-1dae-ae54-40478a993fc2 Version: $LATEST
2019-09-26T20:49:05.464Z	b3ed7724-be8d-1dae-ae54-40478a993fc2	INFO	triggered call: 2019-09-26T20:49:05.464Z
END RequestId: b3ed7724-be8d-1dae-ae54-40478a993fc2
```

But the expected scheduled invocation as declared in the `template.yaml` did not trigger. Did I declare it incorrectly? Or is this a bug? Or is it neither because scheduled lambda is not supported in [`SAM local`](https://aws.amazon.com/about-aws/whats-new/2017/08/introducing-aws-sam-local-a-cli-tool-to-test-aws-lambda-functions-locally/)?

Thanks.

**Comment by awood45** [comment]
https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api does not contain a "Schedule" property, so it makes sense that you can only invoke it using the API. If you want this to be BOTH an Api-based function and a scheduled function, you'll need two different Events. For example:

```yaml
TestScheduledFunction:
      Type: AWS::Serverless::Function
      Properties:
        Handler: app.test
        Events:
          PromechApi:
            Type: Api
            Properties:
              Path: /test
              Method: any
          PromechScheduled:
            Type: Schedule
              Schedule: rate(1 minute)
```

**Comment by jfuss** [comment]
Closing as there was been no response. Feel free to reopen if this is still an issue.

**Comment by petrucristescu** [comment]
Hello,

What if I want to schedule a call to an API method?
Can this be achieved?

In this particular call I'm not sure what exactly is called when defined scheduled time expires.
What if there are multiple API functions and one single schedule event? Which one will be called?

```
PromechScheduled:
            Type: Schedule
            Properties:
              Schedule: rate(1 minute)
```

I'm thinking about some warming up scenario when I want to "ping" and get back a "pong".

Thanks
