### ISSUE TITLE
Difficult and inconvenience in working with ruby and bundle gems

### ISSUE THREAD

**Issue by kimyu92** [awslabs/aws-sam-cli#1442]
### Description
Here is an example of ruby folder structure

sam-app/
|-- api/
|   |-- v1/
|   |   |-- endpoint.rb
|   |   |-- helper.rb
|   |   |-- helper2.rb
|-- template.yaml
|-- Gemfile
|-- Gemfile.lock
|-- vendor/
|   |-- bundle/

`endpoint.rb` snippet:
```ruby
require 'rubygems'
require 'bundler/setup'
require_relative 'helper'

def lambda_handler(event:, context:)
end
```

`helper.rb` snippet:
```ruby
require_relative 'helper2'
```

`helper2.rb` snippet:
```ruby
require 'some_legit_gem'
```

without using sam, pure ruby structure, it's possible to run the code with command below
```bash
bundle install --path vendor/bundle
ruby app/v1/endpoint.rb
```

### Steps to reproduce
```bash
bundle install # create vendor/bundle at root folder which is good
sam build
sam local start-api
```

### Observed result
```
{
  "errorType": "Init\u003cLoadError\u003e",
  "errorMessage": "cannot load such file -- some_legit_gem",
  "stackTrace": [
    "/var/lang/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'",
    "/var/lang/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'",
```

### Expected result

Doesn't require `vendor/bundle` to be same level as actual lambda handler or provide a simple entry point to lookup vendor folder

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Mac OS 10.14.6
2. Sam CLI: 0.22.0:

**Comment by awood45** [comment]
Can you show me your `template.yaml` file? As a short-term workaround, I strongly suspect that if you put your `Gemfile` into the `api/` folder and just run `sam build`, everything will work. But for a deeper explanation, I'd need to see your template file.

**Comment by kimyu92** [comment]
@awood45 Here is the `template.yaml`, I personally felt having `Gemfile` under `api` or `api/v1` or maybe having on both locations (root & codeuri subfolder) doesn't seem right to me. I would definitely want to hear more about it.

```yaml
Resources:
  EndpointFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/v1/
      Handler: endpoint.lambda_handler
      Runtime: ruby2.5
      Events:
        Endpoint:
          Type: Api
          Properties:
            Path: /api/v1/endpoint
            Method: get
      Environment:
        Variables:
          SOME_KEY: !Ref SomeKey
```
