### ISSUE TITLE
Add command to generate swagger/OpenAPI from SAM template

### ISSUE THREAD

**Issue by jlhood** [awslabs/aws-sam-cli#1473]
### Describe your idea/feature/enhancement

SAM CLI should provide a command to generate a swagger/OpenAPI definition file given a SAM template. SAM has this great convenience feature where it authors the swagger/OpenAPI document for you at deploy time. However, there are good reasons why a project would want to have access to the document as part of the build process. One example is if the project wants to use [swagger-codegen](https://swagger.io/tools/swagger-codegen/) to generate code from the swagger file. If you want to do this with SAM today, you have to hand-manage the OpenAPI doc yourself rather than let SAM manage it for you.

### Proposal

No SAM spec changes should be needed for this, but the SAM translator library should do most of the heavy lifting here and add a library method to fetch the OpenAPI doc for a given SAM template and API logicalId (default to ServerlessRestApi). Then SAM CLI can add a command (`sam generate openapi`?) that calls this method and outputs the generated OpenAPI doc.

**Comment by wing328** [comment]
FYI. You can also use [OpenAPI Generator](https://github.com/OpenAPITools/openapi-generator) to generate API clients, server stubs, documentation, schemas, etc. We just released v4.1.3 last week: https://twitter.com/oas_generator/status/1180123829626003456. Please check it out and let us know if you've any feedback.

Disclosure: I'm the top contributor to both OpenAPI Generator and Swagger Codegen.

**Comment by nweajoseph** [comment]
Is this feature request asking for SAM to somehow do what apigateway endpoint does? https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-export-api.html#api-gateway-export-api-download-swagger-yaml

```shell
GET /restapis/<restapi_id>/stages/<stage_name>/exports/oas30
Host: apigateway.<region>.amazonaws.com
Accept: application/yaml

```

**Comment by blade2005** [comment]
> Is this feature request asking for SAM to somehow do what apigateway endpoint does? https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-export-api.html#api-gateway-export-api-download-swagger-yaml
> 
> ```shell
> GET /restapis/<restapi_id>/stages/<stage_name>/exports/oas30
> Host: apigateway.<region>.amazonaws.com
> Accept: application/yaml
> ```

Yes, I'd like to be able to generate the swagger docs prior to deploy.

**Comment by Ada-Nick** [comment]
I would also like this feature!

**Comment by cionz0** [comment]
+1

**Comment by ck-developer** [comment]
+1

**Comment by shalinisree** [comment]
+1

**Comment by dmitriyzhuk** [comment]
+1

**Comment by hafizglasswall** [comment]
It would simply greatly +1

**Comment by dcabib** [comment]
# GitHub Issue #1473 Comment - OpenAPI Compliance Discussion

Hey SAM CLI team! 👋

I've implemented `sam generate openapi` for issue #1473 - it's working and tested (94% coverage, 5,956 tests passing, verified on complex production templates). **But I need architectural guidance on 5 OpenAPI compliance decisions before opening the PR.**

## What Works Today

Command successfully extracts OpenAPI from SAM templates via SAM Translator:
```bash
sam generate openapi -t template.yaml --openapi-version 3.0 -o api.yaml
```

**Tested on production template**: 35 API routes, 6 Lambda functions, Cognito authorization - all generated correctly with proper CORS and security configuration.

## The 5 Compliance Gaps (Need Community Direction)

### 1. CloudFormation Intrinsic Functions

**Current Output**:
```yaml
info:
  title: {Ref: AWS::StackName}
paths:
  /users:
    get:
      x-amazon-apigateway-integration:
        uri: {Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UserFunction.Arn}/invocations}
security:
  - CognitoAuth:
      providerARNs: [{Ref: UserPoolArn}]
```

**OpenAPI Standard**: Plain resolved values
```yaml
info:
  title: "My API"
paths:
  /users:
    get:
      # No CloudFormation syntax
```

**Why It Happens**: SAM Translator preserves template structure - doesn't resolve CloudFormation parameters or functions.

**The Problem**: CloudFormation refs make the spec less usable for swagger-codegen and other OpenAPI tooling.

**Options**:
- **A)** Keep CloudFormation refs as-is (shows template structure, matches SAM deployment spec)
- **B)** Resolve all refs using --parameter-overrides (cleaner output, but requires all parameters be provided)
- **C)** Add `--resolve-refs` flag for user choice (default: keep refs)

**My Recommendation**: **Option C** - Default to raw output (accurate to SAM), add flag for resolved version if needed.

---

### 2. AWS-Specific Extensions

**Current Output**:
```yaml
paths:
  /users/{userId}:
    get:
      x-amazon-apigateway-integration:
        httpMethod: POST
        type: aws_proxy
        uri: {Fn::Sub: arn:aws:apigateway:...}
      x-amazon-apigateway-auth:
        type: cognito_user_pools

x-amazon-apigateway-gateway-responses:
  DEFAULT_4XX:
    responseParameters:
      gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
```

**OpenAPI Standard**: No vendor-specific extensions

**Why It Happens**: These ARE the actual API Gateway deployment configurations that SAM generates. They show exactly how the API will be deployed.

**The Problem**: Pure OpenAPI specs shouldn't have vendor extensions.

**Options**:
- **A)** Keep AWS extensions (shows real deployment details, valuable for infrastructure docs)
- **B)** Strip all x-amazon-apigateway-* fields (cleaner for generic tooling)
- **C)** Add `--strip-aws-extensions` flag for choice

**My Recommendation**: **Option A** - Keep extensions. Reasons:
1. They're accurate and valuable for understanding deployment
2. Most OpenAPI tools (including swagger-codegen) ignore unknown extensions
3. Removing them loses important configuration information
4. If someone needs pure OpenAPI, they can post-process

---

### 3. Swagger 2.0 vs OpenAPI 3.0

**Current Output**: Swagger 2.0 format (what SAM Translator generates)
```yaml
swagger: '2.0'
securityDefinitions:  # Swagger 2.0 location
  CognitoAuth: {...}
```

**Why**: SAM Translator hasn't migrated to OpenAPI 3.0 yet - still outputs Swagger 2.0.

**Current Implementation**: Added `--openapi-version` flag
- `--openapi-version 2.0`: Raw SAM Translator output (Swagger 2.0)
- `--openapi-version 3.0`: Auto-converts to OpenAPI 3.0 (moves securityDefinitions → components.securitySchemes)

**Default**: OpenAPI 3.0 (modern standard)

**Question**: Is defaulting to 3.0 correct, or should we default to 2.0 (matches SAM Translator output)?

**My Recommendation**: **Keep default as 3.0** - Most tooling prefers OpenAPI 3.0. Users can specify 2.0 if needed.

---

### 4. Missing `servers` Section

**Current Output**: No servers array

**OpenAPI 3.0 Requirement**:
```yaml
servers:
  - url: https://api.example.com/v1
    description: Production API
```

**Why Missing**: API Gateway assigns URL at **deployment time**. Pre-deployment, the actual URL doesn't exist yet.

**The Problem**: 
- OpenAPI 3.0 spec technically requires servers section
- But we can't know the URL from just the SAM template
- URL format: `https://{apiId}.execute-api.{region}.amazonaws.com/{stage}`
- Where `{apiId}` is assigned by CloudFormation at deploy time

**Options**:
- **A)** Omit entirely (current) - Spec is technically invalid per OpenAPI 3.0
- **B)** Add placeholder: `https://example.com/REPLACE_AFTER_DEPLOYMENT`
- **C)** Add template URL: `https://{apiId}.execute-api.{region}.amazonaws.com/{stage}` with note
- **D)** Only include if user provides `--api-url` parameter

**My Recommendation**: **Option C** - Add template URL with CloudFormation-style variables. Shows the structure, users can substitute `{apiId}` and `{stage}` after deployment. Example:
```yaml
servers:
  - url: "https://{apiId}.execute-api.{region}.amazonaws.com/{stage}"
    description: API Gateway endpoint (replace {apiId} and {stage} after deployment)
    variables:
      apiId: {description: "API Gateway REST API ID", default: "REPLACE_ME"}
      stage: {description: "Deployment stage", default: "dev"}
```

---

### 5. Missing Request/Response Schemas

**Current Output**:
```yaml
paths:
  /users/{userId}:
    get:
      responses: {}  # Completely empty!
    post:
      responses: {}  # No request body schema either
```

**OpenAPI Standard**: Should define detailed schemas
```yaml
paths:
  /users/{userId}:
    get:
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
            pattern: '^[0-9]+$'
      responses:
        200:
          description: User found
          content:
            application/json:
              schema:
                type: object
                properties:
                  userId: {type: string}
                  name: {type: string}
                  email: {type: string, format: email}
        404:
          description: User not found
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name: {type: string}
```

**Why Missing**: SAM templates define ROUTES but not DATA MODELS. Example SAM template:
```yaml
Resources:
  UserFunction:
    Type: AWS::Serverless::Function
    Properties:
      Events:
        CreateUser:
          Type: Api
          Properties:
            Path: /users
            Method: post
            # NO RequestModel or ResponseModel defined!
```

SAM supports RequestModel/ResponseModel, but most templates don't use them.

**The Real Problem**: This is a **SAM template limitation**, not a command limitation. If schemas aren't in the template, we can't generate them.

**Options**:
- **A)** Leave empty (current) - Accurate to template, documents limitation
- **B)** Generate generic placeholder schemas (`type: object`)
- **C)** Require users to add RequestModel/ResponseModel to SAM template if they want schemas
- **D)** Add `--infer-schemas` flag to attempt inference from Lambda function type hints (complex, fragile)

**My Recommendation**: **Option A** - Leave empty and document. Reasons:
1. Being accurate to template is better than making up schemas
2. Users needing schemas should define models in SAM template
3. swagger-codegen works fine without schemas (generates generic types)
4. Option D (inference) is scope creep and error-prone

---

## Summary of Recommendations

| Gap | Proposed Solution | Reasoning |
|-----|------------------|-----------|
| CloudFormation refs | Keep, add `--resolve-refs` flag later if needed | Accuracy first, convenience optional |
| AWS extensions | Keep all extensions | Valuable config info, ignored by tools anyway |
| Swagger vs OpenAPI | Default to 3.0, flag for 2.0 ✅ | Modern standard preferred |
| servers section | Add template URL with variables | Shows structure, user substitutes after deploy |
| Schemas | Leave empty, document | Can't generate what's not in template |

## The Trade-Off

**Current approach**: Generates "deployment-faithful" OpenAPI
- Shows what SAM actually creates
- Includes AWS config
- Has CloudFormation template structure

**Alternative**: "tooling-friendly" OpenAPI  
- Resolved values
- No AWS stuff  
- Pure standard compliance
- Less accurate to actual deployment

**Question**: Which philosophy should SAM CLI adopt? The original issue says "use swagger-codegen" but doesn't specify which approach.

## What I'm Asking

1. **Agree/disagree with the 5 recommendations above?**
2. **Should we do this iteratively?** (MVP now, enhancements based on feedback)
3. **Any other compliance concerns I missed?**

Branch is ready: https://github.com/dcabib/aws-sam-cli/tree/feat/generate-openapi-command  
(Blocked by AWS security hook on unrelated file, but code is committed locally)

Happy to adjust based on team direction! 🚀
