### ISSUE TITLE
Connecting to Mongo causes timeout

### ISSUE THREAD

**Issue by olingern** [awslabs/aws-sam-cli#148]
Thanks for the awesome tool! 

I've been having issues with sending a response after opening a mongo connection. In my implementation, I'm connecting to mlab and can verify that it actually works / connects. The issue is sending the response after Mongoose connects to mongodb. 

I've put together some sample code below that you should be able to replace the `mongodbUrl` with a valid connections string to replicate.

FWIW, I'm using mlab; however, I did see connection rejections when attempting to connect to localhost even thought my mongo instance was running locally and other applications could use it.

Sample code:

**index.js**
```javascript
exports.handler = (event, context, callback) => {
  const mongodbUrl = 'mongodb://?:?@mongodbUrl:port/myMongoDb';
  mongoose.Promise = Promise;
  mongoose.connect(mongodbUrl, { useMongoClient: true });

  const db = mongoose.connection;
  db.once('open', () => callback(null, { statusCode: 200, body: "OK"} ));
}
```

**template.yml**
```yml
AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: |
  An example RESTful service
Resources:
  ExampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs6.10
      Timeout: 5
      Handler: index.handler
      Events:
        ListCustomers:
          Type: Api
          Properties:
            Path: /
            Method: any
```

**Error logged to the console**:

```
2017/09/28 12:25:24 Invoking index.handler (nodejs6.10)
START RequestId: dd17310c-21de-18a9-7c3f-311a8ba489a3 Version: $LATEST
2017/09/28 12:25:30 Function index.handler timed out after 5 seconds
2017/09/28 12:25:30 Error invoking nodejs6.10 runtime: io: read/write on closed pipe
```
