### ISSUE TITLE
ScriptLocation is not updated for Glue::Job when building

### ISSUE THREAD

**Issue by wnkz** [awslabs/aws-sam-cli#1537]
### Description

When running `sam build` ; `AWS::Glue::Job` `Command.ScriptLocation`'s path is not updated in `.aws-sam/build/template.yaml`.

My real template includes Serverless::Functions so I need to run build and cannot just use package.
This works just fine for other resources supported by `sam package` (e.g. `AWS::CloudFormation::Stack`) but not for Glue Jobs.

### Steps to reproduce

template.yml
```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  GlueJob:
    Type: AWS::Glue::Job
    Properties:
      GlueVersion: '1.0'
      MaxCapacity: 5
      Command:
        Name: glueetl
        PythonVersion: '3'
        ScriptLocation: glue.py
      Role: !GetAtt GlueServiceRole.Arn

  GlueServiceRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /service-role/
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - glue.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
```

```
sam build
```

### Observed result

.aws-sam/build/template.yaml
```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  GlueJob:
    Type: AWS::Glue::Job
    Properties:
      GlueVersion: '1.0'
      MaxCapacity: 5
      Command:
        Name: glueetl
        PythonVersion: '3'
        ScriptLocation: glue.py
      Role:
        Fn::GetAtt:
        - GlueServiceRole
        - Arn
  GlueServiceRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /service-role/
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - glue.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
```

Command.ScriptLocation is left untouched.

### Expected result

.aws-sam/build/template.yaml
```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  GlueJob:
    Type: AWS::Glue::Job
    Properties:
      GlueVersion: '1.0'
      MaxCapacity: 5
      Command:
        Name: glueetl
        PythonVersion: '3'
        ScriptLocation: ../../glue.py
      Role:
        Fn::GetAtt:
        - GlueServiceRole
        - Arn
  GlueServiceRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /service-role/
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - glue.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
```

Command.ScriptLocation should be updated.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: macOS 10.15.1
2. `sam --version`: SAM CLI, version 0.31.1
