### ISSUE TITLE
Error: PythonPipBuilder:ResolveDependencies - {pyodbc==4.0.27(sdist)}

### ISSUE THREAD

**Issue by thanuj11** [awslabs/aws-sam-cli#1577]
Error Installing python pyodbc package in aws sam. (cmd used: sam build --use-container)

Error:
Build Failed
Error: PythonPipBuilder:ResolveDependencies - {pyodbc==4.0.27(sdist)}

Details:
Python Version: 3.6
sam version: SAM CLI, version 0.31.0
aws cli version: aws-cli/1.16.251

pip install pyodbc works, but when I include pyodbc in requirements.txt and run sam build --use-container it errors out.

Any comments or fixes to solve this issue

**Comment by TheSriram** [comment]
This is interesting, when building within the container we look for manylinux wheels. can you reproduce on a normal sam build as well?

**Comment by thanuj11** [comment]
I tried using sam build, but sam build also failed

command: sam build

**Build Failed
Error: PythonPipBuilder:ResolveDependencies - {pyodbc==4.0.27(wheel)}**

**Comment by jfuss** [comment]
@thanuj11 `pyodbc` does not have linux wheels, so we have to build from source. I would assume this is the part that is failing (some missing dependency or something?). The path forward I can think of is to manually build it and vendor the dependency directly or place it in a layer that you can use.

**Comment by thanuj11** [comment]
@jfuss, yes, It is not able to find Linux wheels for pyodbc. I will try to build manually and use it as a layer. 

Thanks.

**Comment by plantusd** [comment]
I've built pyodbc and trying to attach as lambda layer, but I always get these two errors:
ImportError: libodbc.so.2: cannot open shared object file: No such file or directory
or this
AttributeError: module 'pyodbc' has no attribute 'paramstyle'
Here's he layer
[pyodbc.zip](https://github.com/awslabs/aws-sam-cli/files/3908330/pyodbc.zip)

Thanks in advance!

**Comment by sanathkr** [comment]
@plantusd I am not sure what's going on. Do you need to modify LD_LIBRARY_PATH env vars to point to .so files in the layer?

**Comment by Mike-Nahmias** [comment]
I was able to get pyodbc working by using alexanderluiscampino's layer [here](https://github.com/alexanderluiscampino/lambda-layers).

**Comment by danyags** [comment]
> I was able to get pyodbc working by using alexanderluiscampino's layer [here](https://github.com/alexanderluiscampino/lambda-layers).

@Mike-Nahmias How did you setup your project?

**Comment by Mike-Nahmias** [comment]
@danyags The pyodbc folder I linked to is in the root of my project and then I add it as a layer in my template:

```
Resources:
  pyodbcLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: pyodbcLayer
      Description: Layer containing pyodbc and SQL driver, as sam build failed to compile
      ContentUri: pyodbc_layer/
      CompatibleRuntimes: [python3.7]
```

**Comment by danyags** [comment]
@Mike-Nahmias I downloaded the file, pyodbc folder is in the root of my project, but I'm getting an error: No module named 'pyodbc'. 

my template.yaml file is as below

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  pyodbcLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: pyodbcLayer
      Description: Layer containing pyodbc and SQL driver, as sam build failed to compile
      ContentUri: pyodbc/
      CompatibleRuntimes: [python3.7]
      
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.7
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn

**Comment by Mike-Nahmias** [comment]
@danyags I think you forgot to add the layer to your function. Sorry, I didn't make that clear. It should look something like this:

```
Resources:
  pyodbcLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: pyodbcLayer
      Description: Layer containing pyodbc and SQL driver, as sam build failed to compile
      ContentUri: pyodbc/
      CompatibleRuntimes: [python3.7]

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.7
      Layers:
        - !Ref pyodbcLayer
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
```
