### ISSUE TITLE
sam deploy incorrectly displays parameter override when value has a space in it

### ISSUE THREAD

**Issue by jlhood** [awslabs/aws-sam-cli#1652]
### Description

sam deploy does not properly display parameter overrides read in from samconfig.toml if the parameter value contains a space.

### Steps to reproduce

1. Create a SAM template with a String parameter Message.
1. Use `sam deploy --guided` to deploy the template. When prompted to fill in a value for parameter Message, enter `test message`. When prompted to save the values to samconfig.toml, say yes.
1. Run `sam deploy` again without the `--guided` flag.

### Observed result

% sam deploy

```
	Deploying with following values
	===============================
	Stack name                 : test
	Region                     : us-east-1
	Confirm changeset          : True
	Deployment s3 bucket       : aws-sam-cli-managed-default-samclisourcebucket-<random chars>
	Capabilities               : ["CAPABILITY_IAM"]
	Parameter overrides        : {'Message': 'test'}
```

### Expected result

Parameter overrides should have said `{'Message': 'test message'}`. Note, this only appears to be a display bug in SAM CLI. The changeset created by SAM contains the right value for the parameter ("test message").

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: macOS High Sierra
2. `sam --version`: 0.37.0

**Comment by jfuss** [comment]
@jlhood Thanks for the issue. Glad it only seems like a UX bug but something we should defiantly address.

**Comment by sanathkr** [comment]
I was not able to repro the bug. @jlhood can you also paste a sample SAM template?

**Comment by jlhood** [comment]
I run `sam init`, then select "AWS Quick Start Templates" -> python3.8 -> Hello World Example. Then add a Message parameter of type string. Here's the template after doing that:

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

Parameters:
  Message:
    Type: String

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
```

Note, the first time I run `sam deploy --guided`, the parameter override displays correctly. It's the second time I run `sam deploy` without `--guided` that the parameter override value is truncated.
