### ISSUE TITLE
sam deploy always requires capabilities parameter

### ISSUE THREAD

**Issue by rayko** [awslabs/aws-sam-cli#1675]
Hello, facing a small problem with the `sam deploy` command under v0.37.0. Currently returns the following output:

```
        Deploying with following values
        ===============================
        Stack name                 : test-app
        Region                     : us-east-1
        Confirm changeset          : False
        Deployment s3 bucket       : None
        Capabilities               : null
        Parameter overrides        : {}

Initiating deployment
=====================
Error: Failed to create changeset for the stack: test-app, Parameter validation failed:
Invalid type for parameter Capabilities, value: None, type: <class 'NoneType'>, valid types: <class 'list'>, <class 'tuple'>
```
The exact same template deploys fine on v0.33.1. Here's the template:

```
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources:
  TestApp:
    Type: 'AWS::Lambda::Function'
    Properties:
      Description: 'FIXME test_app Simple Function'
      Environment:
        Variables:
          APP_ENV: 'production'
      FunctionName: 'test_app'
      Handler: 'app/lambda.execute'
      MemorySize: 128
      Role: 'arn:aws:iam::***:role/LambdaGeneric'
      Runtime: 'python3.7'
      Timeout: 60
```

Could it be that the default value for capabilities was removed?
https://github.com/awslabs/aws-sam-cli/commit/02ea704fa06c938f6598220936df0f7f9951c99a#diff-cee8562a5cceb15939365bf969f8c005L157

I also noticed it sets `CAPABILITY_IAM` as default in some cases on the deploy command:
https://github.com/awslabs/aws-sam-cli/blob/v0.37.0/samcli/commands/deploy/command.py#L303

Was that a hidden default for the capabilities parameter? If that's the case, I can just feed that as a param in my deploy command and move on, but I'm a bit unsure. Any advice?
