### ISSUE TITLE
Unable to import module in attached docker container

### ISSUE THREAD

**Issue by FieryCod** [awslabs/aws-sam-cli#1725]
### Description
When I dockerize `sam` I'm unable to import the application module. Host `sam local start-api` works fine.

### Steps to reproduce
Create following files and put it to some folder like `example`. Navigate to `example` and run `docker-compose up`

**Dockerfile:**
```
FROM ubuntu:bionic-20191202 as dev

RUN apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*

RUN apt-get update \
    && apt-get install -y --no-install-recommends ca-certificates curl file g++ git locales make uuid-runtime \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && localedef -i en_US -f UTF-8 en_US.UTF-8 \
    && useradd -m -s /bin/bash linuxbrew \
    && echo 'linuxbrew ALL=(ALL) NOPASSWD:ALL' >>/etc/sudoers

USER linuxbrew
ENV PATH=/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:$PATH \
SHELL=/bin/bash

RUN git clone https://github.com/Homebrew/brew /home/linuxbrew/.linuxbrew/Homebrew \
    && mkdir /home/linuxbrew/.linuxbrew/bin \
    && ln -s ../Homebrew/bin/brew /home/linuxbrew/.linuxbrew/bin/ \
    && brew config

RUN brew update --verbose && brew upgrade --verbose

USER root

RUN apt-get update && apt-get upgrade -y
RUN apt-get remove docker docker-engine docker.io
RUN apt-get install -f -y --no-install-recommends \
    cmake scons ruby \
    autoconf automake autoconf-archive \
    gettext libtool flex \
    libbz2-dev libcurl4-openssl-dev \
    libexpat-dev libncurses-dev \
    apt-utils g++ gcc build-essential \
    gettext-base rsync curl wget groff \
    less unzip ca-certificates bash \
    python-dev musl-dev git gawk bison make inotify-tools python file \
    docker.io apt-transport-https

ENV NVM_DIR=/nvm
ENV NODE_VERSION=12.14.0

RUN sudo gpasswd -a root docker

RUN brew update --verbose && brew upgrade --verbose

RUN brew tap aws/tap
RUN brew install aws-sam-cli awscli

# Install nvm with node and npm
RUN mkdir -p /nvm

RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.2/install.sh | bash \
    && . $NVM_DIR/nvm.sh \
    && nvm install $NODE_VERSION \
    && nvm alias default $NODE_VERSION \
    && nvm use default \
    && npm install -g yarn

ENV NODE_PATH=$NVM_DIR/v$NODE_VERSION/lib/node_modules
ENV PATH=$NVM_DIR/versions/node/v$NODE_VERSION/bin:$PATH

WORKDIR /app
EXPOSE 4000 8080

RUN npm install -g yarn

COPY package.json` ./

RUN yarn

COPY . .

ARG NODE_ENV
ENV NODE_ENV=${NODE_ENV:-development}
```

**docker-compose.yml**
```
version: '3.7'

services:
  lambda:
    restart: always
    environment:
      - SAM_CLI_TELEMETRY=0
    build: .
    command: bash -c "sam local start-api -p 4000 --host 0.0.0.0 --debug"
    ports:
      - "4000:4000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:Z
      - .:/app:Z
      - ~/.aws:/root/.aws:Z
```

**package.json**
```
{
  "name": "personal",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT"
}
```

**index.js**
```
exports.handler = async (event, context) => {
    return {
        statusCode: 200,
        body: 'Test'
    };
};
```

**template.yml**
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: nodejs12.x
    Timeout: 15
    MemorySize: 128

Resources:
  SampleEndpoint:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: index.handler
      Events:
        SampleEvent:
          Type: Api
          Properties:
            Cors: true
            Path: /
            Method: get
```

### Observed result
```
lambda_1  | Found one Lambda function with name 'SampleEndpoint'
lambda_1  | Invoking index.handler (nodejs12.x)
lambda_1  | No environment variables found for function 'SampleEndpoint'
lambda_1  | Environment variables overrides data is standard format
lambda_1  | Loading AWS credentials from session with profile 'None'
lambda_1  | Resolving code path. Cwd=/app, CodeUri=./
lambda_1  | Resolved absolute path to code is /app
lambda_1  | Code /app is not a zip/jar file
lambda_1  | Skipping building an image since no layers were defined
lambda_1  | 
lambda_1  | Fetching lambci/lambda:nodejs12.x Docker container image......
lambda_1  | Mounting /app as /var/task:ro,delegated inside runtime container
lambda_1  | Starting a timer for 15 seconds for function 'SampleEndpoint'
lambda_1  | 2020-01-14T13:27:30.854Z	undefined	ERROR	Uncaught Exception 	{"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module 'index'\nRequire stack:\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js","stack":["Runtime.ImportModuleError: Error: Cannot find module 'index'","Require stack:","- /var/runtime/UserFunction.js","- /var/runtime/index.js","    at _loadUserApp (/var/runtime/UserFunction.js:100:13)","    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)","    at Object.<anonymous> (/var/runtime/index.js:43:30)","    at Module._compile (internal/modules/cjs/loader.js:956:30)","    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)","    at Module.load (internal/modules/cjs/loader.js:812:32)","    at Function.Module._load (internal/modules/cjs/loader.js:724:14)","    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)","    at internal/main/run_main_module.js:17:11"]}
```
### Expected result
I do expect that it works the same as when I run it in host environment.

1. OS: Fedora 31 (Workstation Edition)
2. `sam --version`: host SAM CLI, version 0.40, in docker SAM CLI, version 0.40
