### ISSUE TITLE
AWS::Serverless::Api Custom Domain endpoint bug

### ISSUE THREAD

**Issue by darylounet** [awslabs/aws-sam-cli#1780]
Hi,
I have a custom domain in my AWS::Serverless::Api configured with an EDGE endpoint, but a REGIONAL endpoint is deployed.

Here is my template :
```yaml
  MyAPIApi:
    Type: AWS::Serverless::Api
    Properties:
      Domain:
        CertificateArn: arn:aws:acm:us-east-1:****
        DomainName: api.example.com
        DomainEndpointConfiguration: EDGE
        Route53:
          HostedZoneId: ABCD
      CacheClusterEnabled: false
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: 's3://mybucket/openapi.yml'
      EndpointConfiguration: REGIONAL
      MethodSettings:
        - ResourcePath: '/*'
          HttpMethod: '*'
          MetricsEnabled: false
      MinimumCompressionSize: 10
      Name: 'DEV'
      StageName: 'DEV'
```

The Route53 domain is mapped to the "xxx.execute-api.us-east-1.amazonaws.com" host instead of a xxx.cloudfront.net one.
