### ISSUE TITLE
Circular dependency when Function has Environment and S3 Event refer to S3 bucket

### ISSUE THREAD

**Issue by verdimrc** [awslabs/aws-sam-cli#1794]
### Description

This template produces circular dependency:

```yaml
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Converter

  SAM Template for Converter lambda.

Globals:
  Function:
    Timeout: 900
    MemorySize: 3008

Resources:
  ConverterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: Converter/
      Handler: app.lambda_handler
      Runtime: python3.8
      Environment:
        Variables:
          S3_OUTPUT_PATH: !Ref S3Bucket
      Events:
        CreateAugmentedManifestEvent:
          Type: S3
          Properties:
            Bucket: !Ref S3Bucket
            Events: s3:ObjectCreated:*

  S3Bucket:
    Type: AWS::S3::Bucket

Outputs:
  ConverterFunction:
    Description: "Converter Lambda Function ARN"
    Value: !GetAtt ConverterFunction.Arn
  ConverterFunctionIamRole:
    Description: "Implicit IAM Role created for Converter function"
    Value: !GetAtt ConverterFunctionRole.Arn
```

Error message:

```
Waiting for changeset to be created..
Error: Failed to create changeset for the stack: samtest, ex: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state Status: FAILED. Reason: Circular dependency between resources: [S3Bucket, ConverterFunction, ConverterFunctionCreateAugmentedManifestEventPermission]
```

If only one of Environment or Event exists, then deployment succeeds.

### Steps to reproduce

With the above template, do a `sam deploy --guide`

### Observed result

Please provide command output with `--debug` flag set.

```bash
$ sam deploy --region ap-southeast-1 deploy --stack-name samtest --guided --debug
Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics

Configuring SAM deploy
======================

        Looking for samconfig.toml :  Found
        Reading default arguments  :  Success

        Setting default arguments for 'sam deploy'
        =========================================
        Stack Name [samtest]: 
        AWS Region [ap-southeast-1]: 
        #Shows you resources changes to be deployed and require a 'Y' to initiate deploy
        Confirm changes before deploy [y/N]: 
        #SAM needs permission to be able to create roles to connect to the resources in your template
        Allow SAM CLI IAM role creation [Y/n]: 
        Save arguments to samconfig.toml [Y/n]: 

        Looking for resources needed for deployment: Found!

                Managed S3 bucket: aws-sam-cli-managed-default-samclisourcebucket-1ujzqwwaekale
                A different default S3 bucket can be set in samconfig.toml

        Saved arguments to config file
        Running 'sam deploy' for future deployments will use the parameters saved above.
        The above parameters can be changed by modifying samconfig.toml
        Learn more about samconfig.toml syntax at 
        https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html

        Deploying with following values
        ===============================
        Stack name                 : samtest
        Region                     : ap-southeast-1
        Confirm changeset          : False
        Deployment s3 bucket       : <redacted>
        Capabilities               : ["CAPABILITY_IAM"]
        Parameter overrides        : {}

Initiating deployment
=====================
File with same data is already exists at samtest/058e75f2923f17c3bfcd9186cd97336c. Skipping upload
Stack with id samtest does not exist
File with same data is already exists at samtest/fca9a4d47114757a42f549096eb10883.template. Skipping upload

Waiting for changeset to be created..
Sending Telemetry: {'metrics': [{'commandRun': {'awsProfileProvided': False, 'debugFlagProvided': True, 'region': 'ap-southeast-1', 'commandName': 'sam deploy', 'duration': 10825, 'exitReason': 'ChangeSetError', 'exitCode': 1, 'requestId': '402fd264-d8fd-4c7f-b8d7-fc9edc640e57', 'installationId': '8bd1bde5-7333-4a2b-a6e5-ea36e6134f14', 'sessionId': '90c50b89-4f5c-44a4-b759-c60c9d8dcccb', 'executionEnvironment': 'CLI', 'pyversion': '3.7.6', 'samcliVersion': '0.41.0'}}]}
HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Error: Failed to create changeset for the stack: samtest, ex: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state Status: FAILED. Reason: Circular dependency between resources: [S3Bucket, ConverterFunction, ConverterFunctionCreateAugmentedManifestEventPermission]
```

### Expected result

Describe what you expected.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: OSX Mojave
2. `sam --version`: SAM CLI, version 0.41.0

`Add --debug flag to command you are running`

**Comment by jfuss** [comment]
@verdimrc This is an issue with your template not the CLI. 

Some details you can read up on:
* https://aws.amazon.com/premiumsupport/knowledge-center/unable-validate-destination-s3/
* https://github.com/awslabs/serverless-application-model/issues/138
* https://stackoverflow.com/questions/50158593/work-around-circular-dependency-in-aws-cloudformation

Closing as this issue is with the template itself

**Comment by aprilmintacpineda** [comment]
I'm having the same issue, I just followed the documentation https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-s3.html

Here's what that part of the template looks like:

```yaml
profilePictureUploaded:
  Type: AWS::Serverless::Function
  Properties:
    Handler: src/events/s3/profilePictureUploaded.handler
    Layers:
      - !Ref dependencies
    Policies:
      - Statement:
        - Action:
            - s3:GetObject
          Effect: Allow
          Resource:
            - !Join
              - ""
              - - !GetAtt usersS3Bucket.Arn
                - "/*.jpg"
            - !Join
              - ""
              - - !GetAtt usersS3Bucket.Arn
                - "/*.jpeg"
            - !Join
              - ""
              - - !GetAtt usersS3Bucket.Arn
                - "/*.png"
    Events:
      Upload:
        Type: S3
        Properties:
          Bucket: !Ref usersS3Bucket
          Events: s3:ObjectCreated:Put
          Filter:
            S3Key:
              Rules:
                - Name: prefix
                  Value: newUpload_
usersS3Bucket:
  Type: AWS::S3::Bucket
  Properties:
    BucketName: !Join
      - "-"
      - - "users-uploads"
        - !Ref Stage
    CorsConfiguration:
      CorsRules:
      - AllowedHeaders:
          - "*"
        AllowedMethods:
          - GET
          - PUT
          - HEAD
        AllowedOrigins:
          - "*"
    Tags:
      - Key: "what"
        Value: "my s3 bucket"
```

I've changed it in various different ways trying to find the core reason why it happens, but I think the core reason is having `profilePictureUploaded` function, which will be odd
