### ISSUE TITLE
ProvisionedThroughput cannot be empty..

### ISSUE THREAD

**Issue by raymonstah** [awslabs/aws-sam-cli#1815]
### Description
Getting an issue during `sam deploy` saying that ProvisionedThroughput cannot be empty.

### Steps to reproduce

Here's the table defined in my template.yml
```
  GameRoomTable:
    Type: AWS::DynamoDB::Table
    Properties:
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
        - AttributeName: "connection_id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
        - AttributeName: "connection_id"
          KeyType: "RANGE"
      GlobalSecondaryIndexes:
        - IndexName: connection-idx
          KeySchema:
            - AttributeName: "connection_id"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
```

### Observed result

Please provide command output with `--debug` flag set.

### Expected result

Successful deployment

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS:
2. `sam --version`:
SAM CLI, version 0.43.0
