### ISSUE TITLE
Specify globals in --env-vars file will disable Variables in function

### ISSUE THREAD

**Issue by chandlersong** [awslabs/aws-sam-cli#1817]
### Description
#1045 it can work, but it will disable function level variables. I just modify  the go hello word.

envs.json  with Parameters, in lambda,  `SOME_VAR` will be **data**, which is define in the template, it seems it has been disabled

``` json
{
  "HelloWorldFunction": {
    "SOME_VAR": "123",
    "NOT_EXISTS_IN_TEMPLATE": "true"
  },
  "Parameters": {
    "GLOBAL_VAR": "local"
  }
}
```

envs.json  with Parameters, in lambda,  `SOME_VAR` will be **123**,

``` json
{
  "HelloWorldFunction": {
    "SOME_VAR": "123",
    "NOT_EXISTS_IN_TEMPLATE": "true"
  }
}
```

and the template file
```yml
Globals:
  Function:
    Timeout: 60
    Environment:
      Variables:
        GLOBAL_VAR: gobal
Parameters:
  SomeVar:
    Type: String
    Description: My SomeVar
    Default: data
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: aws-lambda/
      Handler: aws-lambda
      Runtime: go1.x
      Tracing: Active
      Events:
        API:
          Type: Api 
          Properties:
            Path: /first
            Method: GET
      Environment: 
        Variables:
          PARAM1: VALUE
          SOME_VAR: !Ref SomeVar
```

in the lambda
I use os.Getenv("SOME_VAR") get the value
