### ISSUE TITLE
Local support for Amazon Linux 2 Layer: arn:aws:lambda:::awslayer:AmazonLinux2

### ISSUE THREAD

**Issue by fabianfett** [awslabs/aws-sam-cli#1890]
### Describe your idea/feature/enhancement

Hi,

to test if my custom lambda runtime still works on Amazon Linux 2, I would like to include the layer `arn:aws:lambda:::awslayer:AmazonLinux2` in my local tests. 

My template looks like this:

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:

  HelloWorldLambdaSecret:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda.zip
      Runtime: provided
      Handler: "whocares"
      MemorySize: 256
      Layers:
      - arn:aws:lambda:::awslayer:AmazonLinux2
      - arn:aws:lambda:eu-central-1:426836788079:layer:Swift:11
```

✅ `sam deploy` works great

‼️ `sam local invoke` fails:

```bash
$> sam local invoke                                                                                                     
Error: arn:aws:lambda:::awslayer:AmazonLinux2 is an Invalid Layer Arn.
```

### Proposal

It would be lovely if `arn:aws:lambda:::awslayer:AmazonLinux2` could also be used locally.
