### ISSUE TITLE
Local Deployment of api-gateway does not respect stage variables

### ISSUE THREAD

**Issue by stevenj** [awslabs/aws-sam-cli#1903]
If I define stage variables for the api-gateway like so:

```YAML
Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      TracingEnabled: True
      Variables:
        logging : debug
```

And I deploy in AWS i get the following in the lambda api event:
```json
"stageVariables": {
        "logging": "debug"
    },
```

However if i deploy for local test.  I only get:
```json
"stageVariables": null,
```

The local deployment is not respecting the stageVariables which breaks any application which requires them.
