### ISSUE TITLE
Execute functions with roles specified in template

### ISSUE THREAD

**Issue by tobiasfeil** [awslabs/aws-sam-cli#1941]
I have a function that sends an email with ses, and I specified in the template, among others:
```
Resources:
  EmailFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: lambda_handlers.email.lambda_handler
      Runtime: python3.7
      Policies:
        - CloudWatchFullAccess
        - AmazonSESFullAccess
```
Remotely, this works, as an implicit role is created with the specified policies attached. But locally, it tries to execute as the user specified in ~/.aws/config. It would feel more consistent to me if it used the same role locally and remotely, is this possible?
