### ISSUE TITLE
Degradation of parameter-overrides option

### ISSUE THREAD

**Issue by imatakeharuhiko** [awslabs/aws-sam-cli#1953]
### Description

The parameter-overrides option of the sam deploy command doesn't look to work on Ver. 0.48.0.
The versions earlier than 0.48.0 work properly.

### Steps to reproduce

```
sam deploy \
    --debug \
    --template-file $1 \
    --stack-name gs2-${X_GS2_SERVICE//_/-}-lambda \
    --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM \
    --region=$X_GS2_REGION \
    --profile gs2-$X_GS2_ENV \
    --parameter-overrides Gs2CoreLayerVersion=$GS_CORE_LAYER_VERSION Service=${X_GS2_SERVICE//_/-} Gs2Region=$X_GS2_REGION \
        Gs2Environment=$X_GS2_ENV
```

The environment variables are properly set.

Excerpt of the template:

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: |
  gs2-gateway

Parameters:
  Gs2CoreLayerVersion:
    Type: Number
    Description: Version of GS2-Core Lambda Layer
  Service:
    Type: String
    Description: service
  Gs2Environment:
    Type: String
    Description: dev or live
  Gs2Region:
    Type: String
    Description: ap-northeast-1

Mappings:
  CertificationArn:
    ap-northeast-1:
      live: arn:aws:acm:ap-northeast-1:258965805804:certificate/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
      dev: arn:aws:acm:ap-northeast-1:193652665524:certificate/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    us-east-1:
      live: arn:aws:acm:us-east-1:258965805804:certificate/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
      dev: arn:aws:acm:us-east-1:193652665524:certificate/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    eu-west-1:
      live: arn:aws:acm:eu-west-1:258965805804:certificate/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
      dev: arn:aws:acm:eu-west-1:193652665524:certificate/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    ap-southeast-1:
      live: arn:aws:acm:ap-southeast-1:258965805804:certificate/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
      dev: arn:aws:acm:ap-southeast-1:193652665524:certificate/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

Conditions:
  IsLive:
    !Equals [!Ref Gs2Environment, live]

Resources:
  Domain:
    Type: AWS::ApiGateway::DomainName
    Properties:
      DomainName:
        !If [
          "IsLive",
          !Join ['.', [!Ref Service, !Ref 'AWS::Region', 'gen2', 'gs2io', 'com']],
          !Join ['.', [!Join ['-', [!Ref Service, !Ref Gs2Environment]], !Ref 'AWS::Region', 'gen2', 'gs2io', 'com']]
        ]
      EndpointConfiguration:
        Types:
          - REGIONAL
      RegionalCertificateArn: !FindInMap ['CertificationArn', !Ref 'AWS::Region', !Ref Gs2Environment]

Outputs:
  Api:
    Value: !GetAtt
      - Domain
      - RegionalDomainName
```

### Observed result

```
Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics

	Deploying with following values
	===============================
	Stack name                 : gs2-****-lambda
	Region                     : **************
	Confirm changeset          : False
	Deployment s3 bucket       : None
	Capabilities               : ["CAPABILITY_IAM", "CAPABILITY_NAMED_IAM"]
	Parameter overrides        : {'Gs2CoreLayerVersion': '49', 'Service': '****', 'Gs2Region': '**************', 'Gs2Environment': 'dev'}

Initiating deployment
=====================
Property CodeUri of PublicHandlerFunction is already a S3 URL
Property CodeUri of PrivateHandlerFunction is already a S3 URL
Property DefinitionUri of Api is already a S3 URL
Collected default values for parameters: {}
Unable to resolve property RegionalCertificateArn: OrderedDict([('Fn::FindInMap', ['CertificationArn', OrderedDict([('Ref', 'AWS::Region')]), OrderedDict([('Ref', 'Gs2Environment')])])]). Leaving as is.
Unable to resolve property Value: OrderedDict([('Fn::GetAtt', ['Domain', 'RegionalDomainName'])]). Leaving as is.
9 resources found in the template
Sending Telemetry: {'metrics': [{'commandRun': {'awsProfileProvided': True, 'debugFlagProvided': True, 'region': '**************', 'commandName': 'sam deploy', 'duration': 508, 'exitReason': 'InvalidLayerVersionArn', 'exitCode': 1, 'requestId': 'fe2845af-8e42-49d4-a66b-4c1a59ba14a3', 'installationId': 'a7812eee-560e-4e8f-aba0-bf08b5153128', 'sessionId': '95b22ab1-c97d-4da2-8342-a30fba2d9b09', 'executionEnvironment': 'CLI', 'pyversion': '3.7.7', 'samcliVersion': '0.48.0'}}]}
HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Error: arn:aws:lambda:us-east-1:123456789012:layer:gs2-core:Gs2CoreLayerVersion is an Invalid Layer Arn.
```

### Expected result

No error if the client version is earlier than 0.48.0.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Windows 10 WSL 2 or circleci/python3.7 Docker image
2. `sam --version`: 0.48.0
