### ISSUE TITLE
Local Invoke with referenced layer (zip file) doesn't work

### ISSUE THREAD

**Issue by Shamshiel** [awslabs/aws-sam-cli#2016]
### Description

A local invoke of the simple _hello world_ (with axios enabled) lambda (nodesj) fails if the node_modules are in a lambda layer. 

#### Background
I came across this problem after I tried to locally invoke a lambda function with a template.yml that was synthesized with the AWS CDK and the option `--no-staging`. The code works fine deployed to AWS but not with local invoke. It only works locally if there are no modules referenced in the lambda.

### Steps to reproduce

1. `sam init` (nodejs12.x / Hello World Example)
2. modify the hello-world/app.js to use axios (remove the comments)
3. `npm install` in the hello-world directory
4. create a nodejs folder, move the node_modules folder in it
5. zip the nodejs folder (for example as nodejs.zip)
6. remove the node_modules folder in the hello-world directory
7. modify the template.yml (see below)
8. `sam local invoke -d 5858`

#### template.yml (partial)
```
Resources:
  HelloWorldFunctionLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleRuntimes:
        - nodejs12.x
      ContentUri: ..\nodejs.zip
      Description: My layer
      LayerName: my-layer
      LicenseInfo: MIT

  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Layers:
        - !Ref HelloWorldFunctionLayer
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
```

### Observed result

The local invoke fails because the axios module cannot be found.

```
PS C:\Users\<USER>\Documents\Repository\Sandbox\sam-app> sam local invoke -d 5858 --debug
Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
local invoke command is called
No Parameters detected in the template
3 resources found in the template
Found Serverless function with name='HelloWorldFunction' and CodeUri='hello-world/'
Found one Lambda function with name 'HelloWorldFunction'
Invoking app.lambdaHandler (nodejs12.x)
No environment variables found for function 'HelloWorldFunction'
Environment variables overrides data is standard format
Loading AWS credentials from session with profile 'None'
Resolving code path. Cwd=C:\Users\<USER>\Documents\Repository\Sandbox\sam-app, CodeUri=hello-world/
Resolved absolute path to code is C:\Users\<USER>\Documents\Repository\Sandbox\sam-app\hello-world
Code C:\Users\<USER>\Documents\Repository\Sandbox\sam-app\hello-world is not a zip/jar file
HelloWorldFunctionLayer is a local Layer in the template
Resolving code path. Cwd=C:\Users\<USER>\Documents\Repository\Sandbox\sam-app, CodeUri=.
Building image...
Requested to skip pulling images ...

Mounting C:\Users\<USER>\Documents\Repository\Sandbox\sam-app\hello-world as /var/task:ro,delegated inside runtime container
Setting up SIGTERM interrupt handler
Debugger listening on ws://0.0.0.0:5859/f1d77abb-e746-4c0e-b881-6b90fc2b280b
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
2020-05-31T08:39:51.119Z        undefined       ERROR   Uncaught Exception      {"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module 'axios'\nRequire stack:\n- /var/task/app.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js","stack":["Runtime.ImportModuleError: Error: Cannot find module 'axios'","Require stack:","- /var/task/app.js","- /var/runtime/UserFunction.js","- /var/runtime/index.js","    at _loadUserApp (/var/runtime/UserFunction.js:100:13)","    at Object.load (/var/runtime/UserFunction.js:140:17)","    at Object.<anonymous> (/var/runtime/index.js:43:30)","    at Module._compile (internal/modules/cjs/loader.js:1130:14)","    at Object..js (internal/modules/cjs/loader.js:1153:10)","    at Module.load (internal/modules/cjs/loader.js:977:32)","    at Function._load (internal/modules/cjs/loader.js:877:14)","    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)","    at internal/main/run_main_module.js:18:47"]}
START RequestId: c809e15e-a73e-1b05-b668-3d652ab6f14a Version: $LATEST
END RequestId: c809e15e-a73e-1b05-b668-3d652ab6f14a
REPORT RequestId: c809e15e-a73e-1b05-b668-3d652ab6f14a     Init Duration: 67025.69 ms      Duration: 1.75 ms       Billed Duration: 100 ms Memory Size: 128 MB     Max Memory Used: 42 MB  

{"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module 'axios'\nRequire stack:\n- /var/task/app.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js"}
Sending Telemetry: {'metrics': [{'commandRun': {'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam local invoke', 'duration': 69491, 'exitReason': 'success', 'exitCode': 0, 'requestId': '81f473bf-cb39-4423-b972-f73b0aec569b', 'installationId': '086fe330-030a-4f34-98ef-dd775cf9c614', 'sessionId': 'd19b019c-7a39-41e1-a4f3-25e7b19bd721', 'executionEnvironment': 'CLI', 'pyversion': '3.7.6', 'samcliVersion': '0.52.0'}}]}
HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
```
Shouldn't there be a `Decompressing nodejs.zip` log entry somewhere in this output?

### Expected result

I expected the local invoke to use my zipped lambda layer.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Microsoft Windows 10 Pro 10.0.18363
2. `sam --version`: SAM CLI, version 0.52.0
