### ISSUE TITLE
Layers is being checked during build for custom macro and failing

### ISSUE THREAD

**Issue by jbpratt78** [awslabs/aws-sam-cli#2026]
Opened a separate issue from my previous comment. 
```yaml
Transform:
  - "AWS::Serverless-2016-10-31"
  - PipLayer
Resources:
  DepLayer:
    Type: "AWS::Lambda::PipLayer"
    Properties:
      BucketName: test
      CompatibleRuntimes:
        - python3.8
      LayerName: camelcase
      Package:
        name: camelcase
        version: "0.2"
  Function:
    Type: "AWS::Serverless::Function"
    Properties:
      CodeUri: src/
      Handler: app.handler
      Layers:
        - !Ref DepLayer
```
`Error: DepLayer is an Invalid Layer Arn.`
I have a custom macro for provisioning Layers from Pip packages, the above code fails to build. I'm not really sure of what the best behavior, if any, for SAM would be here.

`SAM CLI, version 0.43.0`

**Comment by jbpratt78** [comment]
As discussed in #samdev Slack with @bjorg, a workaround is to move the `PipLayer` transform to only apply to the `DepLayer` resource. Things work as intended then. Feel free to close if nothing is to be done here.

**Comment by jbpratt78** [comment]
I think I spoke too soon. I was making a mistake and localizing the transformation, this doesn't seem to work, I am still receiving `Error: DepLayer is an Invalid Layer Arn.` on validation. (sam build)

```yaml
Transform:
  - "AWS::Serverless-2016-10-31"

Resources:
  DepLayer:
    Type: PythonLayer
    Properties:
      BucketName: test
      CompatibleRuntimes:
        - python3.8
      LayerName: camelcase
      Package:
        name: camelcase
        version: "0.2"
    Transform:
      Name: PythonLambdaLayer

  Function:
    Type: "AWS::Serverless::Function"
    Properties:
      CodeUri: src/
      Handler: app.handler
      Layers:
        - Ref: DepLayer
      MemorySize: 128
      Runtime: python3.8
      Timeout: 30
```
