### ISSUE TITLE
Serverless::LayerVersion Makefile issue (not packaging build code)

### ISSUE THREAD

**Issue by jbpratt78** [awslabs/aws-sam-cli#2032]
### Description
Migrating to utilize the makefile feature released in 0.5.0. I think I am just doing something wrong, but I copied the documentation pretty closely. The goal is to simply install a Pip dependency.

### Steps to reproduce
```
httpx/
├── Makefile
└── requirements.txt
```
```yaml
  HttpxDepLayer:
    Type: AWS::Serverless::LayerVersion
    Metadata:
      BuildMethod: makefile
    Properties:
      LayerName: httpx
      Description: dependency
      ContentUri: httpx/
      CompatibleRuntimes:
        - python3.7
```
```
~/ cat httpx/Makefile
build-HttpxDepLayer:
    mkdir -p "$(ARTIFACTS_DIR)/python"
    python -m pip install -r requirements.txt -t "$(ARTIFACTS_DIR)/python"

~/ cat httpx/requirements.txt
httpx~=0.13.3
```

```
sam build
sam deploy
# download the layer deployed and unzip
```
### Observed result

```
~/ unzip httpx-d1b46166-e79c-40ab-809a-cc3d78bb2c7b.zip
Archive:  httpx-d1b46166-e79c-40ab-809a-cc3d78bb2c7b.zip
  inflating: requirements.txt
  inflating: Makefile
```

### Expected result

Packaged artifacts into layer
### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)
1. OS: Linux
2. `sam --version`: SAM CLI, version 0.52.0
