### ISSUE TITLE
Event Type S3 doesn't support name reference

### ISSUE THREAD

**Issue by solivaf** [awslabs/aws-sam-cli#206]
Hi all,

I am trying to use Event Source S3 Type with Bucket property value as name and not a reference, but I receive an error from SAM

`Failed to create the changeset: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state Status: FAILED. Reason: Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 1. Resource with id [FooFunction] is invalid. Event with id [EntryFileCreated] is invalid. S3 events must reference an S3 bucket in the same template.`

My template.yaml is below.

```
AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  FooFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: EntryFile
      Policies:
        - AmazonS3FullAccess
        - AmazonDynamoDBFullAccess
      Handler: entry.lambda_handler
      Runtime: python3.6
      Events:
        EntryFileCreated:
          Type: S3
          Properties:
            Bucket: foo-bucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: entry/
```

BTW, if I use a Reference (as you can see below) , SAM tries to create a new resource instead of use one that already exists.

```
AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  FooFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: EntryFile
      Policies:
        - AmazonS3FullAccess
        - AmazonDynamoDBFullAccess
      Handler: entry.lambda_handler
      Runtime: python3.6
      Events:
        EntryFileCreated:
          Type: S3
          Properties:
            Bucket: !Ref Bucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: entry/
    Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "foo-bucket"
```
If I use the model above, I receive the error below from CloudFormation.

> The following resource(s) failed to create: [Bucket]. . Rollback requested by user. foo-bucket already exists.

I am not sure if I am mistaken or something but it seems a bug.
