### ISSUE TITLE
AWS::ApiGatewayV2::Stage RouteSettings/LoggingLevel type is an Object, when the docs say it should be a string

### ISSUE THREAD

**Issue by divmgl** [awslabs/aws-sam-cli#2071]
### Description

Pretty straightforward bug. Here's the error I'm getting:

```
Property validation failure: [Value of property {/RouteSettings/LoggingLevel} does not match type {Object}]
```

### Steps to reproduce

```yaml
  SmittenWebsocketApiStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      StageName: !Sub smitten-${Environment}
      ApiId: !Ref SmittenWebsocketApi
      AccessLogSettings:
        DestinationArn: !GetAtt SmittenWebsocketApiLogGroup.Arn
        Format: $context.requestId
      RouteSettings:
        LoggingLevel: INFO
```

The docs state that the logging level can be `INFO`, `ERROR`, or `OFF`. 

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-apigatewayv2-stage-routesettings.html

Although I can modify this through the console, I worry about manually doing things with resources that are managed by CloudFormation.

**Comment by awood45** [comment]
This is not an AWS SAM or AWS SAM CLI issue. I would recommend [providing feedback on the documentation](https://docs-feedback.aws.amazon.com/feedback.jsp?hidden_service_name=API%20Gateway&topic_url=http://docs.aws.amazon.com/en_us/AWSCloudFormation/latest/UserGuide/aws-properties-apigatewayv2-stage-routesettings.html) and if needed, contacting AWS Support.

**Comment by joshhoegen** [comment]
@divmgl [divmgl](https://github.com/divmgl), did you ever find a solution to this? I'm running into the same issue.

**Comment by dexter-atob** [comment]
Yep, I stopped using AWS. Problem solved.

Just kidding, that's not why. However I never found a solution for this.

**Comment by divmgl** [comment]
Yep, I stopped using AWS. Problem solved.

Just kidding, that's not why. However I never found a solution for this.

**Comment by joshhoegen** [comment]
Haha! That's hilarious! I hear ya... We're tightly intertwined with AWS, but we've been moving away when we can. I guess I'm on the the source... To think this was supposed to be a 20 min gig, in and out, Morty ;) 

Thanks for the reply, @divmgl 🙏

**Comment by joshhoegen** [comment]
For anyone else that winds up here via Google:

For APIGatewayV2 - Access Logs only (Execution logs aren't available for http).

The AWS documentation is pretty unclear. After some days of shotgun programming, I found this. Here is a Cloudformation with API Gateway v2 that worked for me:

```
MyLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/apigateway/nameOfLogGroupForCloudWatch
      RetentionInDays: 7
MyStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      # Begin CloudWatch
      AccessLogSettings:
        DestinationArn: !GetAtt MyLogGroup.Arn # This points to the log group above
        Format: '{ "requestId": "$context.requestId", "path": "$context.path", "routeKey": "$context.routeKey", "ip": "$context.identity.sourceIp", "requestTime": "$context.requestTime", "httpMethod": "$context.httpMethod","statusCode": $context.status }'
```
