### ISSUE TITLE
FR: Multiple region support for samconfig.toml

### ISSUE THREAD

**Issue by brysontyrrell** [awslabs/aws-sam-cli#2074]
### Describe your idea/feature/enhancement

Most serverless apps I build are designed for active-active across multiple regions. While it's easy to use samconfig.toml to quickly deploy my app within a single region for dev I recently found myself jumping back and forth between two config files for us-east-2 and eu-west-2. The process was cumbersome because there's no argument for passing which toml file to use ( #1615 )and I need to rename the files every time I wanted to deploy to both regions.

If I'm working on an app and I want to have it go to multiple regions when I run `sam deploy` it might be beneficial to be able to store those options in one config file and then the deploy action would iterate over them using the same set of build artifacts locally.

This is actually what we do in CodeBuild jobs in CodePipeline. The script in CodeBuild will run `sam build` and then we loop over a list of regions passed into the env vars and run `sam package` for each. The output deployment templates are then passed to CloudFormation actions in the next stage.

### Proposal

Here's the current `0.1` spec for a config file that's generated:

```toml
version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "my-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-xxxxxxxxxx"
s3_prefix = "my-api"
region = "us-east-2"
profile = "my_profile"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Foo=\"Bar\""
```

I understand there is a semi-hidden feature where other environments can be set besides `default` with some overrides. Maybe the `.deploy.parameters` can be extended with region/environment specific overrides.

```toml
version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "my-api"
s3_prefix = "my-api"
profile = "my_profile"
capabilities = "CAPABILITY_IAM"
[default.deploy.parameters.us-east-2]
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-xxxxxxxxxx"
parameter_overrides = "Foo=\"Bar\""
[default.deploy.parameters.eu-west-2]
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-xxxxxxxxxx"
parameter_overrides = "Foo=\"Baz\""
```

The presence of the region suffix would trigger package/deploy logic for multiple regions.
