### ISSUE TITLE
Clarification for Sam Deploy Validation Error

### ISSUE THREAD

**Issue by Gunt-r** [awslabs/aws-sam-cli#2081]
I received the following error when attempting to deploy my lambda application. My issue is that I am not able to understand what it is asking me to do in order to fix the error.

`Error: Failed to create changeset for the stack: {stack-name}, An error occurred (ValidationError) when calling the CreateChangeSet operation: Stack:arn:aws:cloudformation:ap-southeast-2:014009325916:stack/{stack-name}/f2212bf0-bb41-11ea-8ef3-0aa7af0536b6 is in ROLLBACK_COMPLETE state and can not be updated.`

Could someone please clarify this for me

**Comment by timoschilling** [comment]
Is this the first deploy of that stack or an update deployment?

**Comment by c2tarun** [comment]
Usually this error indicates that there is some issue with the template. Please let us know if you need more help around this? We might need to take a look at your template for more info.

**Comment by Gunt-r** [comment]
Here is my template file

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A tradingview alert wrapper that interprets alerts and makes trades according to them.

Globals:
    Function:
        # CodeUri: function/.
        # Runtime: python3.8
        # Policies:
        #     - AWSLambdaFullAccess
        # Tracing: Active
        # Timeout: 30
        Environment:
            Variables:
                APIKEY: ""
                SECRETKEY: ""


Resources:
    tradeFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: app.trade
            Description: The primary execution function
            CodeUri: function/.
            Runtime: python3.8
            Policies:
                - AWSLambdaFullAccess
            Tracing: Active
            Timeout: 60
            Events:
                inputResponse:
                    Type: Api
                    Properties:
                        Path: /trade
                        Method: post
                        

    printAccountBalanceFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: function/.
            Runtime: python3.8
            Policies:
                - AWSLambdaFullAccess
            Tracing: Active
            Timeout: 30
            Handler: app.print_account_balance
            Description: Returns account balance over time or trade
            Events:
                inputResponse:
                    Type: Api
                    Properties:
                        Path: /print_account_balance
                        Method: get
    startTradesFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: function/.
            Runtime: python3.8
            Policies:
                - AWSLambdaFullAccess
            Tracing: Active
            Timeout: 30
            Handler: app.start_trades
            Description: Resets trade log for a fresh start
            Events:
                inputResponse:
                    Type: Api
                    Properties:
                        Path: /start_trades
                        Method: get                   
    retrieveTradeLogFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: function/.
            Runtime: python3.8
            Policies:
                - AWSLambdaFullAccess
            Tracing: Active
            Timeout: 30
            Handler: app.retrieve_trade_log
            Description: Return all the trade logs in the dyanamoDB database
            Events:
                inputResponse:
                    Type: Api
                    Properties:
                        Path: /retrieve_trade_log
                        Method: get
    # test-function:
    #     Type: AWS::Serverless::Function
    #     Properties:
    #         CodeUri: test/.
    #         Runtime: python3.8
    #         Policies:
    #             - AWSLambdaFullAccess
    #         Tracing: Active
    #         Timeout: 30
    #         Handler: test.test
    #         Description: test
    #         Events:
    #             inputResponse:
    #                 Type: Api
    #                 Properties:
    #                     Path: /retrieve_trade_log
    #                     Method: get
    # print-trade-log-function:
    #     Type: AWS::Serverless::Function
    #     Properties:
    #         CodeUri: function/.
    #         Runtime: python3.8
    #         Policies:
    #             - AWSLambdaFullAccess
    #         Tracing: Active
    #         Timeout: 30
    #         Handler: app.print_trade_log
    #         Description: Returns all data EXCEPT TRADES.
    #         Events:
    #             inputResponse:
    #                 Type: Api
    #                 Properties:
    #                     Path: /print_trade_log
    #                     Method: get
```

**Comment by c2tarun** [comment]
So your template looks right to me, I copied your template and changed **CodeUri** and **Handler** of all the functions and deployment worked for me. Probably there is some handler missing or some typo in the name.

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A tradingview alert wrapper that interprets alerts and makes trades according to them.

Globals:
    Function:
        # CodeUri: function/.
        # Runtime: python3.8
        # Policies:
        #     - AWSLambdaFullAccess
        # Tracing: Active
        # Timeout: 30
        Environment:
            Variables:
                APIKEY: ""
                SECRETKEY: ""


Resources:
    tradeFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: app.lambda_handler
            Description: The primary execution function
            CodeUri: hello_world/
            Runtime: python3.8
            Policies:
                - AWSLambdaFullAccess
            Tracing: Active
            Timeout: 60
            Events:
                inputResponse:
                    Type: Api
                    Properties:
                        Path: /trade
                        Method: post
                        

    printAccountBalanceFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: hello_world/
            Runtime: python3.8
            Policies:
                - AWSLambdaFullAccess
            Tracing: Active
            Timeout: 30
            Handler: app.lambda_handler
            Description: Returns account balance over time or trade
            Events:
                inputResponse:
                    Type: Api
                    Properties:
                        Path: /print_account_balance
                        Method: get
    startTradesFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: hello_world/
            Runtime: python3.8
            Policies:
                - AWSLambdaFullAccess
            Tracing: Active
            Timeout: 30
            Handler: app.lambda_handler
            Description: Resets trade log for a fresh start
            Events:
                inputResponse:
                    Type: Api
                    Properties:
                        Path: /start_trades
                        Method: get                   
    retrieveTradeLogFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: hello_world/
            Runtime: python3.8
            Policies:
                - AWSLambdaFullAccess
            Tracing: Active
            Timeout: 30
            Handler: app.lambda_handler
            Description: Return all the trade logs in the dyanamoDB database
            Events:
                inputResponse:
                    Type: Api
                    Properties:
                        Path: /retrieve_trade_log
                        Method: get
    # test-function:
    #     Type: AWS::Serverless::Function
    #     Properties:
    #         CodeUri: test/.
    #         Runtime: python3.8
    #         Policies:
    #             - AWSLambdaFullAccess
    #         Tracing: Active
    #         Timeout: 30
    #         Handler: test.test
    #         Description: test
    #         Events:
    #             inputResponse:
    #                 Type: Api
    #                 Properties:
    #                     Path: /retrieve_trade_log
    #                     Method: get
    # print-trade-log-function:
    #     Type: AWS::Serverless::Function
    #     Properties:
    #         CodeUri: function/.
    #         Runtime: python3.8
    #         Policies:
    #             - AWSLambdaFullAccess
    #         Tracing: Active
    #         Timeout: 30
    #         Handler: app.print_trade_log
    #         Description: Returns all data EXCEPT TRADES.
    #         Events:
    #             inputResponse:
    #                 Type: Api
    #                 Properties:
    #                     Path: /print_trade_log
    #                     Method: get
```
