### ISSUE TITLE
DefinitionUri for AWS::Serverless::StateMachine errors if it contains a - character

### ISSUE THREAD

**Issue by jbesw** [awslabs/aws-sam-cli#2091]
Hyphen/dash character in DefinitionUrl causes error - error message does not indicate this is the problem.

### Description

Deploying a template with a Uri like this:

```
  ResizerStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: definitions/1-resizer.asl.json
```
...causes the error "Property validation failure: [Encountered unsupported properties in {/}: [DefinitionUri]]" Removing the dash, it deploys correctly.

### Steps to reproduce

Deploy a state machine with a dash in the DefinitionUri.

### Observed result

 "Property validation failure: [Encountered unsupported properties in {/}: [DefinitionUri]]" 

### Expected result
Either:
1. Successful deployment (dash accepted).
2. Error indicating that the dash character is problematic, not the "/" character as shown.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Windows
2. `sam --version`: 0.53.0

`Add --debug flag to command you are running`
