### ISSUE TITLE
HTTP Proxy integration to Lambda is incorrect.

### ISSUE THREAD

**Issue by gantzm** [awslabs/aws-sam-cli#244]
Using a template like the following (see below) the "resource" attribute of the proxy JSON should be set to `/rest/getId/{token}`.  

When issuing a GET call to `/rest/getId/MyId`, I would expect to see:

```
{
  "resource": "/rest/getId/{token}",
  "path": "/rest/getId/MyId"
}
```
Instead I receive the following:
```
{
  "resource": "/rest/getId/MyId",
  "path": "/rest/getId/MyId"
}
```
This is contrary to how HTTP Proxy works with API Gateway. 

Sample Template:

```
Resources:
  MyResource:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.MyHandler
      CodeUri: MyHandler.zip
      Runtime: java8
      MemorySize: 512
      Timeout: 30
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        GetId:
          Type: Api
          Properties:
            Path: /rest/getId/{token}
            Method: get
```
