### ISSUE TITLE
CF functions in template cause json error in start-api

### ISSUE THREAD

**Issue by nzoschke** [awslabs/aws-sam-cli#321]
I have a template with a function with a conditional environment variable

```yaml
  MyFunction:
    Properties:
      CodeUri: ./handlers/my/main.zip
      Environment:
        Variables:
          WEB_URL:
            !If
            - WebDomainNameSpecified
            - !Sub https://${WebDomainName}
            - !Join [., [!Sub "http://${WebBucket}", !FindInMap [RegionMap, !Ref 'AWS::Region', S3WebsiteEndpoint]]]
```

I can't run this locally:

```
$ aws-sam-local local start-api -n env.json
ERROR: json: cannot unmarshal array into Go value of type string
ERROR: json: cannot unmarshal array into Go value of type string
...
ERROR: None of the Serverless functions in your SAM template were able to be mounted. See above for errors.
```

I see issue #194 discusses this, however I am specifying an env file but still getting the json error.

**Comment by StefanSmith** [comment]
I have encountered similar issues in the past and they were resolved by using the long-form intrinsic functions rather than short form (e.g. Fn::FindInMap: rather than !FindInMap), especially for nested function expressions.

**Comment by nzoschke** [comment]
Thanks, the long-form is working for me too:

```yaml
  WebUrl:
    Value:
      !If
      - WebDomainNameSpecified
      - !Sub https://${WebDomainName}
      - Fn::Sub: ["http://${WebBucket}.${Endpoint}", {Endpoint: !FindInMap [RegionMap, !Ref "AWS::Region", S3WebsiteEndpoint]}]
```
