### ISSUE TITLE
Executing nested lambda function on Windows

### ISSUE THREAD

**Issue by IainAdams** [awslabs/aws-sam-cli#356]
Hi,

My project structure is as follows:

    - <project>
        - dist
            - proxies
                - packages
                    - packages-handler.js
        ....
        template.yaml

My template.yaml includes a nodejs6.10 handler as follows:

    Resources:
      Products:
         Type: AWS::Serverless::Function
         Properties:
           Runtime: nodejs6.10
           Handler: ./dist/proxies/packages/packages-handler.handle
           Events:
               ListProducts:
               Type: Api
               Properties:
                    Path: /packages
                    Method: get

I am trying to use SAM Local (v0.2.10) with Docker for Windows (18.03.0-ce-win59). Starting SAM local with 'start-api' seems fine. However, when I hit http://localhost:3000/packages, I simply get:

    2018/04/09 12:22:42 Invoking ./dist/proxies/packages/packages-handler.handle (nodejs6.10)
    2018/04/09 12:22:42 Mounting /c/Repositories/test-lambda as /var/task:ro inside runtime container
    START RequestId: 20b8747c-9a74-1abf-335f-02331adbf176 Version: $LATEST
    Bad handler ./dist/proxies/packages/packages-handler.handle
    END RequestId: 20b8747c-9a74-1abf-335f-02331adbf176
    REPORT RequestId: 20b8747c-9a74-1abf-335f-02331adbf176  Duration: 11.90 ms      Billed Duration: 
    100 ms Memory Size: 128 MB     Max Memory Used: 28 MB
    2018/04/09 12:22:44 Function returned an invalid response (must include one of: body, headers or 
    statusCode in the response object): %!s(<nil>)

My handler has a console.log('TEST') as the first line so I should expect to see that. If I put the same handler in the root of the directory, like so:

    - <project>
        packages-handler.js
        ....
        template.yaml

and update the template.yaml, I get the correct output:

     START RequestId: 631ec935-caf0-12c7-698c-af121182a432 Version: $LATEST
     2018-04-09T11:15:06.734Z        631ec935-caf0-12c7-698c-af121182a432    TEST
     END RequestId: 631ec935-caf0-12c7-698c-af121182a432

It must be something to do with mounting the directories into the docker container. C:\ is shared in Docker Settings and I am using Powershell (same result with Git bash too tho).

Any help much appreciated.

Thanks
Iain

**Comment by bottemav** [comment]
The `Handler` property points to the function within your Node.js file that is called to begin execution. The `CodeUri` property defines the location of the Node.js file. 
This should work:
```
Resources:
  Products:
     Type: AWS::Serverless::Function
     Properties:
       Runtime: nodejs6.10
       Handler: packages-handler.handle
       CodeUri: ./dist/proxies/packages
       Events:
           ListProducts:
           Type: Api
           Properties:
                Path: /packages
                Method: get
```
