### ISSUE TITLE
SAM Local testing doesn't work for source inside a folder

### ISSUE THREAD

**Issue by sharji2322** [awslabs/aws-sam-cli#375]
**Description:**

I have set up a Lambda-API project using AWS SAM. My directory structure for the code is as follow -

```
Project
-src
--index.js
-template.yml
-buildspec.yml
```

My template.yml has the following serverless function
```
  DummyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/index.helloWorld
      Runtime: nodejs6.10
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: helloworld
            Method: post
```
This function runs perfectly when I deploy it in AWS. But while using SAM Local I am facing an issue. I get the following error -
```
   Unable to import module 'src/index': Error
    at Function.Module._resolveFilename (module.js:469:15)
```
If I move the index.js to the main root folder and change my template.yml to
```
Project
-index.js
-template.yml
-buildspec.yml
    Properties:
      Handler: index.helloWorld
```
then I am able to run the api using SAM local.

I don't want to put all my functions in the same file and I am trying to split my functions and keep them inside src folder.
