### ISSUE TITLE
Environment variables file doesn't work with start-api

### ISSUE THREAD

**Issue by pcx** [awslabs/aws-sam-cli#381]
My `template.yaml` looks like this:

```
AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  TestFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: test.handler
      Runtime: nodejs8.10
      Events:
        GetSyncObject:
          Type: Api
          Properties:
            Path: /test
            Method: get
```

The `env.json` looks like this:
```
{
    "TestFunction": {
        "ENV_NAME": "development",
        "DATABASE_URL": "http://dynamodb:8000/"
    }
}
```

The `test.js` file looks like this:

```
module.exports.handler = (event, context, callback) => {
  console.log(process.env);
};
```

I am running the command as:
`sam local start-api --env-vars env.json`

The out put in the terminal does not show the env vars from the file specified above. I am using OSX and `aws-sam-local@0.2.11`.
