### ISSUE TITLE
Not Overriding Globals Environment Variable

### ISSUE THREAD

**Issue by sashokbg** [awslabs/aws-sam-cli#382]
Hello,

I have a couple of functions in my template.yml and I have declared a Globals section in which I see all of them have an env variable TABLE_NAME.

Sam does not seem to pick the Globals section when trying to override the env with --env-vars

Thank you for your help

```
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: functions


Globals:
  Function:
    MemorySize: 192
    Timeout: 120
    Environment:
      Variables:
        TABLE_NAME: !Ref JobsTable

Parameters:
  targetStage:
    Description: Define stage to which Lambdas/API Gateways should be deployed.
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - integ
      - prod
    ConstraintDescription: Only stages dev, integ and prod are allowed
  TABLE_NAME:
    Type: String

Resources:
  JobsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "Job-${targetStage}"
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  GetJobList:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "getJobs-${targetStage}"
      Handler: com.airliquide.aries.lambda.handlers.JobHandler::getList
      CodeUri: ./target/functions-1.0-SNAPSHOT.jar
      Policies: AmazonDynamoDBReadOnlyAccess
      Runtime: java8
      Timeout: 100
      Events:
        Api:
          Type: Api
          Properties:
            Path: /job
            Method: get

  CreateJob:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "createJobs-${targetStage}"
      Handler: com.airliquide.aries.lambda.handlers.JobHandler::createJob
      CodeUri: ./target/functions-1.0-SNAPSHOT.jar
      Policies: AmazonDynamoDBFullAccess
      Runtime: java8
      Timeout: 100
      Events:
        Api:
          Type: Api
          Properties:
            Path: /job
            Method: put

  UpdateJob:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "updateJobs-${targetStage}"
      Handler: com.airliquide.aries.lambda.handlers.JobHandler::updateJob
      CodeUri: ./target/functions-1.0-SNAPSHOT.jar
      Policies: AmazonDynamoDBFullAccess
      Runtime: java8
      Timeout: 100
      Events:
        Api:
          Type: Api
          Properties:
            Path: /job
            Method: post
```
