### ISSUE TITLE
Java Handler not found sam 0.3.0

### ISSUE THREAD

**Issue by sashokbg** [awslabs/aws-sam-cli#413]
**Description:**

Hello, since updating to version 0.3 my java lambda cannot find its handler.

**Steps to reproduce the issue:**
1. Update to sam local 0.3 via pip
2. Create a function with java handler
3. Invoke the function from start-api

```
sam local start-api --docker-network=sky-net --env-vars ./env_local.json
```

**Additional environment details (Ex: Windows, Mac, Amazon Linux etc)**
- Ubuntu LTS 17.10
- Our template:

```
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Airliquide Jobs Lambdas

Globals:
  Function:
    MemorySize: 192
    Timeout: 120

Parameters:
  targetStage:
    Description: Define stage to which Lambdas/API Gateways should be deployed.
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - integ
      - prod
    ConstraintDescription: Only stages dev, integ and prod are allowed

Resources:
  JobsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "Job-${targetStage}"
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  GetJobList:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "getJobs-${targetStage}"
      Handler: com.mypackage.JobHandler::getList
      CodeUri: ./target/mypackage-1.0-SNAPSHOT.jar
      Policies: AmazonDynamoDBReadOnlyAccess
      Runtime: java8
      Timeout: 100
      Environment:
        Variables:
          TABLE_NAME: !Ref JobsTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /job
            Method: get
```

**Output of `sam --version`**:
```
SAM CLI, version 0.3.0
```
**Debug logs**:
2018-05-14 14:28:23 Mounting CreateJob at http://127.0.0.1:3000/job [PUT]
2018-05-14 14:28:23 Mounting GetJobList at http://127.0.0.1:3000/job [GET]
2018-05-14 14:28:23 Mounting UpdateJob at http://127.0.0.1:3000/job [POST]
2018-05-14 14:28:23 You can now browse to the above endpoints to invoke your functions. You do not need to restart/reload SAM CLI while working on your functions changes will be reflected instantly/automatically. You only need to restart SAM CLI if you update your AWS SAM template
2018-05-14 14:28:23  * Running on http://127.0.0.1:3000/ (Press CTRL+C to quit)
2018-05-14 14:28:30 Invoking com.mypackage.JobHandler::getList (java8)
2018-05-14 14:28:30 Found credentials in shared credentials file: ~/.aws/credentials
2018-05-14 14:28:30 Decompressing /home/alexander/projects/mypackage/target/mypackage-1.0-SNAPSHOT.jar

Fetching lambci/lambda:java8 Docker container image......
2018-05-14 14:28:33 Mounting /tmp/tmpdCCYam as /var/task:ro inside runtime container
START RequestId: 04199ee0-884e-4f31-a7b2-bc4ec7dd8c13 Version: $LATEST
java.lang.ClassNotFoundException: com.mypackage.handlers.JobHandler
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)

END RequestId: 04199ee0-884e-4f31-a7b2-bc4ec7dd8c13
REPORT RequestId: 04199ee0-884e-4f31-a7b2-bc4ec7dd8c13	Duration: 3.80 ms	Billed Duration: 100 ms	Memory Size: 192 MB	Max Memory Used: 4 MB	
2018-05-14 14:28:34 Function returned an invalid response (must include one of: body, headers or statusCode in the response object). Response received: 
2018-05-14 14:28:34 127.0.0.1 - - [14/May/2018 14:28:34] "GET /job HTTP/1.1" 502 -
