### ISSUE TITLE
v0.3 Breaks Greedy Proxies: `{"errorMessage":"no handler for GET /{proxy+}"}`

### ISSUE THREAD

**Issue by aaronjameslang** [awslabs/aws-sam-cli#434]
**Description:**

Migrating from 0.2.11 to 0.3 breaks my app, giving `{"errorMessage":"no handler for GET /{proxy+}"}` from claudia-api-builder due to lack of route/path information.

**Steps to reproduce the issue:**
Configure a `template.yml` like
```
Resources:
 myfunc:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist
      Handler: index.handler
      Runtime: nodejs6.10
      Timeout: 10
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
        Home:
          Type: Api
          Properties:
            Path: /
            Method: any

```

Then start SAM and `GET /report` or any non-root resource

**Observed result:**
The latest version gives
```
{
  body: null,
  httpMethod: 'GET',
  resource: '/{proxy+}',
  queryStringParameters: null,
  requestContext: {
     httpMethod: 'GET',
     requestId: 'c6af9ac6-7b61-11e6-9a41-93e8deadbeef',
     path: '/{proxy+}',
     extendedRequestId: null,
     resourceId: '123456',
     apiId: '1234567890',
     stage: 'prod',
     resourcePath: '/{proxy+}',
     identity:
      { accountId: null,
        apiKey: null,
        userArn: null,
        cognitoAuthenticationProvider: null,
        cognitoIdentityPoolId: null,
        userAgent: 'Custom User Agent String',
        caller: null,
        cognitoAuthenticationType: null,
        sourceIp: '127.0.0.1',
        user: null },
     accountId: '123456789012'
  },
```

There is no way from this to know the path of the original request.

**Expected result:**
Previous version passed the handler an event like
```
{
  httpMethod: 'GET',
  body: '',
  resource: '/report',
  requestContext: {
     resourcePath: '/report',
     httpMethod: 'GET',
     stage: 'prod',
     identity: { sourceIp: '127.0.0.1:63093' }
   },
```

**Additional environment details (Ex: Windows, Mac, Amazon Linux etc)**

Mac, Docker Version 18.03.1-ce-mac65 (24312)

**Output of `sam --version`**:

SAM CLI, version 0.3.0

**Actions**

I suspect one of `resourcePath`, `resource` or `path` should contain the info needed, and this is likely just a mis-assigned variable some where around https://github.com/awslabs/aws-sam-cli/blob/develop/samcli/local/apigw/service.py#L372

If someone can confirm this is a bug, and perhaps which property should contain the original path, I can look into submitting a PR.

If this is not a bug, how can I get the routing data I need in my handler?
