### ISSUE TITLE
after upgrading to v0.30 error when calling api-gateway

### ISSUE THREAD

**Issue by araker** [awslabs/aws-sam-cli#453]
After upgrading to v0.3.0 I get the following error when calling a method from the api-gateway, 'no module named lambda_entry'. When I revert back to version 0.2.1, the method works again. I had a problem that aws-sam-cli upgraded docker to v3.3, I've downgraded to v2.7 again so that my older docker-compose files work again. Is docker v3.3 required for aws-sam-cli? 

full output log 

START RequestId: 979fa613-5089-40fb-a48c-789510960733 Version: $LATEST
Unable to import module 'lambda_entry': No module named 'lambda_entry'
END RequestId: 979fa613-5089-40fb-a48c-789510960733
REPORT RequestId: 979fa613-5089-40fb-a48c-789510960733 Duration: 0 ms Billed Duration: 100 ms Memory Size: 128 MB Max Memory Used: 18 MB
2018-06-01 16:02:03 No Content-Type given. Defaulting to 'application/json'.

_Gateway template.yml_ 

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda function
Resources:
  someFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_entry.handler
      Runtime: python3.6
      CodeUri: bundle.zip
      Timeout: 300
      Environment:
        Variables:
          AWS_ENVIRONMENT: sandbox
      Events:
        Api:
          Type: Api
          Properties:
            Path: /someFunction
            Method: post
```

_starting gateway_
sam local start-api -p 3000 --docker-network api_default --host 0.0.0.0

the directory structure in the zip file is: 
- lambda_entry.py
- extra libs in the root
- for each dependency a different directory

I'm on linux mint 18.2, docker v2.7.0, docker-compose 1.19.0.
