### ISSUE TITLE
template.yml inside folder breaks 'sam local invoke'... still

### ISSUE THREAD

**Issue by red8888** [awslabs/aws-sam-cli#487]
see this: https://github.com/awslabs/aws-sam-cli/issues/140
Same problem with version: version 0.3.0

Uninstalled sam npm, upgraded to latest sam local with pip (python 2)

Windows 10.

```
sam local invoke blah --template mytemps/mytemp.yaml -e myevents/test.json
Unable to import module 'lambda_function': No module named 'lambda_function'
```

Works when yaml template is in the root of the folder. Do I have to use codeUri or something?

YAML
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  blah:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      Description: ''
      MemorySize: 128
      Timeout: 300
      Role: '......'
      Environment:
        Variables:
          sdfsdfs: sdfsdfsdf

```
