### ISSUE TITLE
sam local: --env-vars parameter does not work with "start-api" subcommand 

### ISSUE THREAD

**Issue by mvinii94** [awslabs/aws-sam-cli#49]
Hi there,

When using this sample: https://aws.amazon.com/blogs/aws/new-aws-sam-local-beta-build-and-test-serverless-applications-locally/

If you try to use the environment variable file (--env-vars) in the command "sam local", it only works with the "invoke" if you try to use the "start-api" the variables are not loaded.

*Command1:

> echo '{"httpMethod": "POST", "body": "{\"vote\": \"spaces\"}"}' |
sam local invoke "VoteSpacesTabs" --env-vars env.json

sam local invoke "VoteSpacesTabs" --env-vars env.json
2017/08/15 14:49:42 0.1.0
2017/08/15 14:49:42 Successfully parsed template.yaml (version 2010-09-09)
2017/08/15 14:49:42 Connected to Docker 1.30
2017/08/15 14:49:42 Fetching lambci/lambda:python3.6 image for python3.6 runtime...
python3.6: Pulling from lambci/lambda
Digest: sha256:66cbc36a528221efd64d5cbe2620a144a3f00172e6a444b36e2a1d975f0ae63c
Status: Image is up to date for lambci/lambda:python3.6
2017/08/15 14:49:46 Reading invoke payload from stdin (you can also pass it from file with --event)
2017/08/15 14:49:46 Invoking lambda_function.lambda_handler (python3.6)
START RequestId: 90f5d6db-6fef-4fb2-bce5-560e003e319f Version: $LATEST
dynamodb.Table(name='spaces-tabs-votes')
{'httpMethod': 'POST', 'body': '{"vote": "spaces"}'}
{'vote': 'spaces'}
END RequestId: 90f5d6db-6fef-4fb2-bce5-560e003e319f
REPORT RequestId: 90f5d6db-6fef-4fb2-bce5-560e003e319f Duration: 165 ms Billed Duration: 200 ms Memory Size: 128 MB Max Memory Used: 26 MB

{"body": "spaces now has 11 votes"}

---

*Command2 (and then, send a POST using curl):

> sam local start-api --env-vars env.json 

Error:
----- error ------
Parameter validation failed:
Invalid length for parameter TableName, value: 0, valid range: 3-inf: ParamValidationError
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 36, in lambda_handler
    ReturnValues='ALL_NEW'
  File "/var/runtime/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/var/runtime/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "/var/runtime/botocore/client.py", line 310, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/runtime/botocore/client.py", line 573, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/var/runtime/botocore/client.py", line 628, in _convert_to_request_dict
    api_params, operation_model)
  File "/var/runtime/botocore/validate.py", line 291, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid length for parameter TableName, value: 0, valid range: 3-inf
----- error -----

Could you please take a look at it ?

Thank you.

**Comment by sanathkr** [comment]
That's weird. Are you using the same env-vars.json as the blog post?

**Comment by heikkis** [comment]
Docker inspect confirms on OSX Docker that no envs are passed to container. Triple checked env.json and template.yaml file match.

If passed as sam commnad line it appears on docker environment and of course works also for OS.getenv in lambda function.


```
{
  "VoteSpacesTabs": {
    "TABLE_NAME": "spaces-tabs-votes",
    "BUCKET_NAME": "mybucket"
  }
}

```

```
AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  VotesTable:
    Type: "AWS::Serverless::SimpleTable"
  VoteSpacesTabs:
    Type: "AWS::Serverless::Function"
    Properties:
      Runtime: python3.6
      Handler: lambda_function.lambda_handler
      Policies: AmazonDynamoDBFullAccess
      Timeout: 10
      Environment:
        Variables:
          TABLE_NAME: !Ref VotesTable
      Events:
        Vote:
          Type: Api
          Properties:
            Path: /
            Method: post
```

**Comment by PaulMaddox** [comment]
I believe this is fixed in the develop branch, but just hasn't been released.

https://github.com/awslabs/aws-sam-local/pull/29
https://github.com/PaulMaddox/aws-sam-local/commit/5f6bb386afbe0154e3270ecd6a9941af618abad3

**Comment by sanathkr** [comment]
Okay, this makes sense. I will release new build to NPM today.

**Comment by sanathkr** [comment]
Duplicate of #28

**Comment by cezarbabin** [comment]
I'm encountering this issue with 0.2.8. Can anyone repro?

**Comment by sashokbg** [comment]
Same problem here with 0.6.0

**Comment by sanathkr** [comment]
Re-opening because people are hitting this bug again

**Comment by sashokbg** [comment]
Hello @sanathkr 

I just did a test and it worked ! 

What I missed was that I needed to declare the environment variable in my function.
It does not just pass any env variable it finds.

Do you think we should probably update the [readme](https://github.com/awslabs/aws-sam-cli/blob/develop/docs/advanced_usage.rst#lambda-environment-variables) ?

Thank you for your help !
Best regards
Alex

**Comment by sanathkr** [comment]
Actually this is already in the readme.. but probably not too explicit (https://github.com/awslabs/aws-sam-cli/blob/develop/docs/advanced_usage.rst#environment-variable-file). 

@sashokbg  would you be interested in sending a PR?

Closing the issue because this is not a bug.

**Comment by scorphus** [comment]
No more docs?

**Comment by scorphus** [comment]
It's not working. Is there any FULL example?

**Comment by LukeShay** [comment]
This should help @scorphus, https://github.com/awslabs/aws-sam-cli/blob/develop/tests/integration/testdata/invoke/vars.json

**Comment by david-christensen** [comment]
FWIW - This seems to work for me only when my env file is in the project root directory, which is also where I'm running the command `sam local start-api --env-vars=.env.json`

It also would not work until I set blank Environment Variables in the template.yml.

It would be nice to be able to use ENV variables only for local development, without having to set them on the function. 🤷‍♂

**Comment by tobiasfeil** [comment]
> It also would not work until I set blank Environment Variables in the template.yml.
Thank you for being the only person on the internet who informs me about this! Why isn't this in the docs??? Not to mention why it's even necessary, which in itself is questionable, but now that it's necessary, please put it in the docs at least. Just wasted me 45mins and I'm probably not the only one

**Comment by mrvladis** [comment]
@david-christensen Thanks a lot for you post. That workaround worked for me as well!

**Comment by 1nfility** [comment]
If it helps anyone, I found out that by setting empty environment variables in the template.yml, the env vars from your JSON environment variables file will get loaded.

```yml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: test

Resources:
  TestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: app.handler
      Runtime: nodejs12.x
      MemorySize: 2048
      Environment:
        Variables:
          TEST_ENV: ""
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: get
```

```json
{
  "TestFunction": {
    "TEST_ENV": "foo"
  }
}
```

With this, TEST_ENV gets loaded, and the value is "foo".

``sam local start-api -n env.json``
