### ISSUE TITLE
Invalid event types fail silently

### ISSUE THREAD

**Issue by mikedeck** [awslabs/aws-sam-cli#513]
**Description:**

If you add an event with an invalid type to a function no error is raised by either `sam validate` or `sam deploy`. You can successfully deploy the template, the stack is created successfully by Cloud Formation and the invalid event is simply ignored.

**Steps to reproduce the issue:**
1. create a template.yaml file with the following contents:
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
    SampleFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: index.handler
            Runtime: nodejs8.10
        Events:
            ExampleEvent:
                Type: AnInvalidType
                Properties: {}
```

2. Run `sam validate`

**Observed result:**
The template is validated successfully

**Expected result:**
An error should be returned stating that `AnInvalidType` is not valid.

**Output of `sam --version`**:
SAM CLI, version 0.4.0
