### ISSUE TITLE
Missing !Sub and !If instrinsic functions

### ISSUE THREAD

**Issue by ericraymond** [awslabs/aws-sam-cli#528]
**Description:**

Related to issue #490, please add support for !Sub !Ref, and a minimal !If implementation for environment vars in serverless function or in a globals section. 

Not having this functionality means copy-paste duplication within a template, maintaining a duplicate template for local execution,  copy-paste duplication to specify env vars on the command line, and/or the inability to override default values of environment variables via parameters at runtime.

Bonus points for supporting all variations expressing the fn in  Yaml and Json 

In 0.3.0 this was refactored and appears only to be supporter in a very limited context (e.g., swagger urls?).

**Output of `sam --version`**: 0.4.0

**Comment by jfuss** [comment]
This is also related to #450 and #476.

Going to update labels.

**Comment by charsleysa** [comment]
@jfuss is there any progress on this?

**Comment by mnapoli** [comment]
@charsleysa exactly! I face the same problem with region and even layer versions (I want to use environment variables for those). Related: https://github.com/awslabs/serverless-application-model/issues/751

**Comment by mnapoli** [comment]
Just a heads up for those interested, `!Ref` has been implemented in #657.

**Comment by jfuss** [comment]
I have (slowly) been working on some Sub support. I have pushed the code to my [branch/repo](https://github.com/jfuss/aws-sam-cli/tree/sub-intrinsics). I have some functional tests that are working but missing:

* Unit tests
* A note/warning on not resolving. This is really important since we cannot resolve commuted properties of resources.
* Integ tests

If anyone is looking for a good way to contribute and need/want sub support, feel free to take what I started as the base.

**Comment by henrikbjorn** [comment]
Running into this also for Layers.

**Comment by joshpeng** [comment]
How do we get `!Ref` to work? I keep running into this:
```
Invalid value in Template for key: MY_ENV_VAR: expected string
```
Here is my `template.yml`:
```yml
Parameters:
  SomeTestParam:
    Type: String
    Default: foobar

...

SomeLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:

      ...

      Environment:
        Variables:
          MY_ENV_VAR: !Ref SomeTestParam
```
I am on SAM CLI v0.19.0.

**Comment by daveykane** [comment]
Also having trouble with !Sub not working with Layers

**Comment by jfuss** [comment]
Release in [v0.21.0](https://github.com/awslabs/aws-sam-cli/releases/tag/v0.21.0).

Closing

**Comment by joshpeng** [comment]
@jfuss not sure I follow how to make this work on v0.21.0. Perhaps I am using it wrong? Thanks for any input.

I have parameters defined for `SSMApiKeyId` and `CfnDeployStage`. `!Sub` works for it in the Policies section of my serverless function, but fails when I try to use it in my environment variable.

```
MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: myfunc/
      Handler: app.lambda_handler
      Runtime: python3.7
      FunctionName: !Sub "${AWS::StackName}-myfunc"
      Description: My lambda
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: !Sub "${SSMApiKeyId}${CfnDeployStage}"
      Layers:
        - arn:aws:lambda:us-east-1:113088814899:layer:Klayers-python37-boto3:3  # Boto3 layer from https://github.com/keithrozario/Klayers
      Environment:
        Variables:
          SSM_API_KEY: !Sub "/${SSMApiKeyId}${CfnDeployStage}"
```
Results in:
```
Invalid value in Template for key: SSM_API_KEY: expected string
An error occurred while deploying a SAM Application. Check the logs for more information by running the "View AWS Toolkit Logs" command from the Command Palette.
```
