### ISSUE TITLE
sam local --env-vars parameter does not work

### ISSUE THREAD

**Issue by milashenko** [awslabs/aws-sam-cli#542]
Env is not passed to Lambda funtion.

**Description:**

**Steps to reproduce the issue:**
1. `sam init -r nodejs8.10` to generate template.yaml with the following in it:
```
Resources:
    HelloWorldFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: hello_world/
            Handler: app.lambda_handler
            Runtime: nodejs8.10
            Environment: 
                Variables:
                    PARAM1: VALUE
            Events:
                HelloWorld:
                    Type: Api
                        Path: /hello
                        Method: get
``` 
2. Change app.js to be:
```
exports.lambda_handler = async (event, context, callback) => {
    callback(null, {
        'statusCode': 200,
        'body': JSON.stringify(process.env)
    })
};
```
3. create file env.json
```
{
  "HelloWorldFunction":{
    "MY_TEST_ENV_PROP": "value"
  }
}
```
4. Run:
```
MY_OTHER_TEST_ENV_PROP="OTHER_VALUE" sam local start-api --debug --port 8000 --env-vars env.json
```
5. Open http://127.0.0.1:8000/hello in browser to see result.

**Observed result:**
No MY_TEST_ENV_PROP and MY_OTHER_TEST_ENV_PROP listed. However the PARAM1 from the template.yaml - is.

**Expected result:**
process.env.MY_TEST_ENV_PROP and process.env.MY_OTHER_TEST_ENV_PROP should exist and be equal to appropriate values as described in https://docs.aws.amazon.com/lambda/latest/dg/test-sam-cli.html

**Additional environment details (Ex: Windows, Mac, Amazon Linux etc)**
Mac,
Python 2.7.10

**Output of `sam --version`**:
$ sam --version
SAM CLI, version 0.4.0
