### ISSUE TITLE
Document how to create a self-cleaning S3 bucket

### ISSUE THREAD

**Issue by Amri91** [awslabs/aws-sam-cli#648]
**Description:**
This [documentation](https://github.com/awslabs/aws-sam-cli/blob/develop/docs/deploying_serverless_applications.rst#packaging-your-application) shows how to create an S3 bucket for packaging the applications. However, if we used that bucket the documented way it will be filled with useless objects and will require maintenance.

**Steps to reproduce the issue:**
1. Use [this](https://github.com/awslabs/aws-sam-cli/blob/develop/docs/deploying_serverless_applications.rst#packaging-your-application) to create the S3
1. Use [this](https://github.com/awslabs/serverless-application-model/tree/master/examples/apps/hello-world) example
1. Run aws cloudformation package ...
1. Edit index.js
1. Run aws cloudformation package ... again

**Observed result:**
Two different files uploaded

**Expected result:**
Eventually, only a single file.

**Work around: versioning**
S3 bucket template, this will expire old versions in 3 days.
```yaml
Resources:
  CodeBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - NoncurrentVersionExpirationInDays: 3
            Status: Enabled
```

An extra step before deploying
```console
aws s3 cp somename.zip s3://$BUCKET_NAME
checksVersion=$(aws s3api list-object-versions --bucket $BUCKET_NAME --prefix somename.zip --max-items 1 | grep VersionId | cut -d'"' -f4 )
# Pass checksVersion to serverless.yaml
```

I do not think having a lifecycle rule that expires all objects based on dates is suitable because if for some reason the lambda function deployment failed and a rollback is required, the rollback will fail because the previous object does not exist anymore.

**Work around: keep last 2 objects**
I haven't figured the exact command for this, but it should do the job.

PS: I opened an issue [here](https://github.com/awslabs/serverless-application-model/issues/557) first but I was redirected here.
