### ISSUE TITLE
Can't test a LambdaFunction, even though it can be packaged

### ISSUE THREAD

**Issue by abrooksv** [awslabs/aws-sam-cli#728]
**Description:**
Sam package can package up local `AWS::Lambda::Function`s but can't test them.

**Steps to reproduce the issue:**
1. Use this template:
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
    
Globals:
    Function:
        Timeout: 10

Resources:
    LambdaFunction:
        Type: AWS::Lambda::Function
        Properties:
            Code: hello_world/build/
            Handler: app.lambda_handler
            Runtime: python3.6

    SamFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: hello_world/build/
            Handler: app.lambda_handler
            Runtime: python3.6
```
2. And this handler in `hello_world/app.py`
```
def lambda_handler(event, context):
    return {
        "statusCode": 200,
        "body": "Hello"
    }
```
3. Run `sam local invoke --no-event SamFunction` and it works
4. Run `sam local invoke --no-event LambdaFunction` and it fails

**Observed result:**
LambdaFunction invoke returns:
```
START RequestId: 29ed1075-9e51-441d-9b2b-d7c7d5468593 Version: $LATEST
Unable to import module 'app': No module named 'app'
END RequestId: 29ed1075-9e51-441d-9b2b-d7c7d5468593
REPORT RequestId: 29ed1075-9e51-441d-9b2b-d7c7d5468593 Duration: 2 ms Billed Duration: 100 ms Memory Size: 128 MB Max Memory Used: 18 MB

{"errorMessage": "Unable to import module 'app'"}
```

**Expected result:**
Both invokes should return:
```
START RequestId: f564546a-3660-43c8-8f4c-a49b892d6d20 Version: $LATEST
END RequestId: f564546a-3660-43c8-8f4c-a49b892d6d20
REPORT RequestId: f564546a-3660-43c8-8f4c-a49b892d6d20 Duration: 616 ms Billed Duration: 700 ms Memory Size: 128 MB Max Memory Used: 26 MB

{"statusCode": 200, "body": "Hello"}
```

Additional Info:
Running package:
```
sam package \
    --template-file template.yaml \
    --output-template-file packaged.yaml \
    --s3-bucket <bucket>
```
Results in this template:
```
AWSTemplateFormatVersion: '2010-09-09'
Globals:
  Function:
    Timeout: 10
Resources:
  LambdaFunction:
    Properties:
      Code:
        S3Bucket: <bucket>
        S3Key: 51455b8457b3f51b015a1dea5bf1e60d
      Handler: app.lambda_handler
      Runtime: python3.6
    Type: AWS::Lambda::Function
  SamFunction:
    Properties:
      CodeUri: s3://<bucket>/51455b8457b3f51b015a1dea5bf1e60d
      Handler: app.lambda_handler
      Runtime: python3.6
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
```

**Additional environment details (Ex: Windows, Mac, Amazon Linux etc)**

**Output of `sam --version`**:
0.6.0

**Optional Debug logs**:

`Add --debug flag to command you are running`
