### ISSUE TITLE
Long function name results in non-obvious stack creation failure

### ISSUE THREAD

**Issue by scoates** [awslabs/aws-sam-cli#731]
**Description:**

When creating a stack that has a long function name, CloudFormation reports that it created the function's IAM Role successfully, then reports that the role doesn't exist:

![](https://files.faculty.co/zX9RRznv.png)

This causes the stack to roll back, and much frustration and confusion.

On a whim, I guessed that my function name must be too long. When I shortened it, my stack creation succeeded. I then created a new SAM template with an excessively long name to reproduce the problem, and this is where we ended up.

The [IAM docs](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_iam-limits.html#reference_iam-limits-entity-length) say that the role name must be 64 characters or fewer. I was running into this problem with a physical role name of `sffrontend-dev-SffrontendFunctionRole-RA330IH5SBL2`, which is 50 characters. So something else must be up.

I realize some of this might be anecdotal evidence, but this is what I've managed to discover in the amount of time I can devote to this problem today. When I shortened the above role to `sffend-dev-SffendFunctionRole-RA330IH5SBL2` (where `RA330IH5SBL2` is assigned by CFN), my deploy succeeded.

Here's the test template with the very long name, in case it's helpful:

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    very-long-name-too-long-for-aws-maybe-lets-see
    
    A short description of the project

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 5
        AutoPublishAlias: live # More info about Safe Deployments: https://github.com/awslabs/serverless-application-model/blob/master/docs/safe_lambda_deployments.rst
        DeploymentPreference:
            Type: Linear10PercentEvery1Minute 


Resources:

    VeryLongNamedFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: test-service-name-very-long/build/
            Handler: app.lambda_handler
            Runtime: python3.6
            Tracing: Active  # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
            Events:
                CatchAll:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /first/{proxy+}
                        Method: any 
            # Policies: # Example inline policy
            #     - Version: "2012-10-17"
            #     Statement:
            #         - Effect: "Allow"
            #         Action:
            #             - "ssm:GetParameter"
            #         Resource:
            #             - "*"
            Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
                Variables:
                    PARAM1: VALUE

    # Sample policy to add additional permissions to your Lambda
    VeryLongNamedFunctionAdditionalPermission:
        Type: "AWS::IAM::Policy"
        Properties:
            PolicyName: "root"
            PolicyDocument:
                Version: "2012-10-17"
                Statement:
                    -
                        Effect: "Allow"
                        Action: "ssm:GetParameters"
                        Resource: "*"
            Roles:
                - !Ref VeryLongNamedFunctionRole # Sample policy to demonstrate Implicit IAM Role created with SAM

Outputs:

    VeryLongNamedApigwURL:
      Description: "API Gateway endpoint URL for Prod environment for VeryLongNamed Function"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/first/proxy"

    VeryLongNamedFunction:
      Description: "VeryLongNamed Lambda Function ARN"
      Value: !GetAtt VeryLongNamedFunction.Arn
```

**Steps to reproduce the issue:**
1. Create a template with a very long function name
2. `sam package --template-file template.yaml --output-template-file packaged.yaml --s3-bucket your-bucket-name`
3. `sam deploy --template-file packaged.yaml --stack-name test-service-name-very-long --capabilities CAPABILITY_IAM`

**Observed result:**

The CFN stack fails to create the function resource because it can't find the IAM role, but it also reports that it has created the IAM role. Then CFN rolls back the stack.

**Expected result:**

Either successful stack creation, or an error message that indicates the problem. (If it is indeed identifier length.)

**Additional environment details** This is on MacOS, but that shouldn't matter.

**Output of `sam --version`**: SAM CLI, version 0.5.0

(If this belongs in the [SAM repository](https://github.com/awslabs/serverless-application-model) instead, I'd be happy to move it. I'm just not sure which part is failing. Maybe it's also a CloudFormation problem? I'm really not sure; it manifested when using the SAM CLI.)
