### ISSUE TITLE
Change in Parameter Default not made on re-deploy (with 0.6.2, regression of #450?)

### ISSUE THREAD

**Issue by jrgm** [awslabs/aws-sam-cli#772]
**Description:**

I believe this was reported as fixed in https://github.com/awslabs/aws-sam-cli/issues/450#issuecomment-432680840 for version `0.6.1`.

However, with 0.6.2, I'm not seeing a change of the default value reflected in the Cloudformation Parameters in the console, or in the Lambda function.

**Steps to reproduce the issue:**

1. with template similar to the one below
2. package and deploy
3. Change the Default from `red` to `blue`
4. Check Parameters on the Cloudformation stack, and the Environment on the Lambda function.

Notes:
1. I've tried this also with `--force-upload`, but don't see a change that way either.
2. If I set `--parameter-overrides Color=blue`, the change is made.

Example template structure:
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  Color:
    Type: String
    Default: 'red'
Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: MyFunction/
      Handler: index.main
      Runtime: nodejs8.10
      Environment:
        Variables:
          COLOR: !Ref Color
      Events:
        Get:
          Type: Api
          Properties:
            Path: /call
            Method: get
```

**Output of `sam --version`**:
```
$ sam --version
SAM CLI, version 0.6.2
```

**Additional environment details (Ex: Windows, Mac, Amazon Linux etc)**

Mac OSX
