### ISSUE TITLE
!FindInMap Does Not Work With Globals

### ISSUE THREAD

**Issue by jmrapp1** [awslabs/aws-sam-cli#826]
I have been trying to get the `FindInMap` functionality to work for over a week now with no success. I have followed many different examples and combinations with no luck. Here is the following `template.yaml` file I am using

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "Test Server"

Parameters:
  Environment:
    Type: string
    Default: local
    AllowedValues:
    - local
    - test
    - prod

Mappings:
  EnvParams:
    "local":
      stage: "local"
      databaseUrl: "mongodb://172.18.0.2:27017/server1"
    "test":
      stage: "test"
      databaseUrl: "mongodb://localhost:27017/server2"
    "prod":
      stage: "prod"
      databaseUrl: "mongodb://localhost:27017/server3"

Globals:
  Function:
    Timeout: 30
    Runtime: nodejs8.10
    Environment:
      Variables:
        STAGE: !Ref Environment
        DB_URL: !FindInMap [EnvParams, !Ref Environment, "databaseUrl"]

... irrelevant functionality down here ...
```

The global `STAGE` variable is set correctly, but the `DB_URL` variable is always blank. I have tried all kinds of combinations without any luck. This does not work with `sam local` or on the AWS API Gateway. I have tried hardcoding different environment names into the `!Ref Environment` function to see if that was the issue with no luck either. I'm at a loss.

**Comment by jmrapp1** [comment]
@jfuss Gotcha OK. Been seeing mixed articles on this functionality. Is there any plan to support this in the future?

**Comment by jfuss** [comment]
@jmrapp1 Yes we want to support this. This was is a regressions between version 0.2.11 and 0.3.0. We have added some of the intrinsics support back in but its not complete just yet. We are looking for help in this area, if you want to take a crack at it.

**Comment by jmrapp1** [comment]
@jfuss Are there any branches you know of that are already working on this that I can add to?

**Comment by DanielRedOak** [comment]
@jfuss are there other known issues with intrinsics? I was trying to do something like:

```
ConversionTable:
    Type: 'AWS::Serverless::SimpleTable'

ConversionDeleteFn:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: delete.handler
      Runtime: ruby2.5
      CodeUri: './conversion'
      Description: Deletes addresses from the DynamoDB table
      MemorySize: 512
      Timeout: 15
      Policies:
      - AWSLambdaExecute # Managed Policy
      - Version: '2012-10-17' # Policy Document
        Statement:
        - Effect: Allow
        Action:
        - dynamodb:BatchWriteItem
        Resource: *
      Environment:
        Variables:
          DYNAMO_TABLE: !Ref ConversionTable
      Events:
        FileInteraction:
          Type: Api
          Properties:
            Path: /conversion
            Method: delete
```

And the `!Ref ConversionTable` comes through blank. If I !Ref a parameter, that is passed in. I can open a different issue if thats preferred.
