### ISSUE TITLE
are dynamic references supposed to work in local commands?

### ISSUE THREAD

**Issue by rhbecker** [awslabs/aws-sam-cli#894]
### Description

I'm not certain whether this is a bug, feature request, or user error. I'm attempting to [use dynamic references to specify template values](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/dynamic-references.html); more specifically, I'm attempting to use them to specify environment variable values for my function. So far, instead of the reference getting parsed and replaced by the looked up value, I'm getting the literal reference back.

### Steps to reproduce

Via the cli, I execute ` aws ssm get-parameter --name ExpValue` and the following is returned, as expected ...

```JSON
{
    "Parameter": {
        "Name": "ExpValue",
        "Type": "String",
        "Value": "helloz!",
        "Version": 1,
        "LastModifiedDate": 1545939038.102,
        "ARN": "arn:aws:ssm:us-west-2:668206432575:parameter/ExpValue"
    }
}
```
In my template, I attempt 2 different ways of accessing the param. I haven't yet found any documentation to support the `SSM_VIA_PARAM` approach. I only included that because it apparently worked for [this person](https://github.com/awslabs/serverless-application-model/issues/48#issuecomment-414391433). For the `SSM_DIRECT` approach, I believe I'm following the [instructions in the cloudformation docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/dynamic-references.html#dynamic-references-ssm), but could be doing something wrong.

```YAML
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: ssm-experiment
Globals:
  Function:
    CodeUri: lambda/src/
    Runtime: nodejs8.10
    Timeout: 3
Parameters:
  SSM:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: ExpValue
Resources:
  ExperimentFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: experiment.handler
      Environment:
        Variables:
          SSM_DIRECT: '{{resolve:ssm:ExpValue:1}}'
          SSM_VIA_PARAM: !Ref SSM
          STATIC: hello
      Events:
        Index:
          Type: Api
          Properties:
            Path: /
            Method: get
```

In my function, I just spit out the environment variable values ...

```JavaScript
exports.handler = async (event, context) => {
  try {
    return {
      statusCode: 200,
      body: JSON.stringify({
        ssm_direct: process.env.SSM_DIRECT,
        ssm_via_param: process.env.SSM_VIA_PARAM,
        static: process.env.STATIC,
      }),
    };
  } catch (err) {
    return err;
  }
};
```

### Observed result

When I execute `sam local start-api` and then visit http://127.0.0.1:3000/, I see ...

```JSON
{
  "ssm_direct": "{{resolve:ssm:ExpValue:1}}",
  "ssm_via_param": "ExpValue",
  "static": "hello"
}
```

### Expected result

I expected `ssm_direct` and `ssm_via_param` to hold the value "helloz!".

### Other notes

I did observe a note in the docs I've linked a couple times that might be relevant, but I don't understand what it means:

> For transforms, such as AWS::Include and AWS::Serverless, AWS CloudFormation does not resolve dynamic references prior to invoking any transforms. Rather, AWS CloudFormation passes the literal string of the dynamic reference to the transform. Dynamic references (including those inserted into the processed template as the result of a transform) are resolved when you execute the change set using the template.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Windows 10
2. `sam --version`: SAM CLI, version 0.10.0
