### ISSUE TITLE
Property Tags in AWS::Serverless::Function will be similar to Tags in CloudFormation

### ISSUE THREAD

**Issue by christiangda** [awslabs/aws-sam-cli#899]
### Description
I was using Tags property for my 'AWS::Serverless::Function' as a similar way I use those in my CloudFormation templates.   I was getting different errors,  after spending time reading the documentation, I notice that Tags in 'AWS::Serverless::Function' is different from CloudFormation templates.

Tags in 'AWS::Serverless::Function' (Map of string to string)
```
      Tags:
        Project: !Ref Project
        Environment: !Ref Environment
        Owner: !Ref Owner
        Company: !Ref Company
```
How I use Tags in CloudFormation templates
```
     Tags:
        - Key: Project
          Value: !Ref Project
        - Key: Environment
          Value: !Ref Environment
        - Key: Owner
          Value: !Ref Owner
        - Key: Company
          Value: !Ref Company

```

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Linux Fedora 29
2. `sam --version`: SAM CLI, version 0.10.0
