### ISSUE TITLE
sam cli is not syncing code changes automatically

### ISSUE THREAD

**Issue by publitas-revolution** [awslabs/aws-sam-cli#920]
### Description
When I run sam cli locally my code changes are not picked up automatically and every time I have to run sam build after every code change. 

### Steps to reproduce
1. From the projects main directory run:

    sam build

2. Then execute: 

    sam local start-api

3. This will load below directory 
     ~/image-resize-lambda/.aws-sam/build/
     But since my main project directory is ~/image-resize-lambda any code changes here are not loaded into the docker container

### Expected result

Any code changes in the parent directory should be readily available in the docker container

1. OSX
2. SAM CLI, version 0.10.0

### SAM template:

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    SAM Template for image resize function
    
Globals:
    Function:
        Timeout: 3
    Api:
      BinaryMediaTypes:
        - image~1gif
        - image~1png
        - image~1jpeg


Resources:
    Imageresize:
        Type: AWS::Serverless::Function 
        Properties:
            CodeUri: ./
            Handler: index.handler
            Runtime: nodejs8.10

            Events:
              Images:
                Type: Api 
                Properties:
                  Path: /images
                  Method: get
```
