### ISSUE TITLE
"sam package" uploads file to s3 even if the Lambda function code hasn't changed

### ISSUE THREAD

**Issue by rongshengfang** [awslabs/aws-sam-cli#946]
**Description:**

When `CodeUri` is set to a local directory where the Lambda function code resides, `sam package` uploads the package to the s3 bucket even if there hasn't been any changes to the local directory. This causes a file to be uploaded to the s3 bucket every time `sam package` is run, even if there isn't any change to the Lambda function code.

Is there any way for `sam` to only upload the file when there are changes?

This is how I use the `sam package` command:
```
sam build --use-container --template FunctionV1.yaml
sam package --s3-bucket ${my_s3_bucket} --output-template-file FunctionV1-packaged.yaml \
    --region ${AWS_REGION}
sam deploy ...
```

Please see below for the function definition:

```
  FunctionV1:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: MyFunctionV1
      Description: MyFunctionV1
      CodeUri: ../src/v1/
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      Timeout: 120
      MemorySize: 128
      AutoPublishAlias: live
```
