### ISSUE TITLE
sam local start-api multiple headers bug

### ISSUE THREAD

**Issue by Padreramnt** [awslabs/aws-sam-cli#951]
### Description

removed duplicated headers from response

### Steps to reproduce

```ts
export async function main() {
  return {
    statusCode: 200,
    body: `sam local start-api multiple headers bug`,
    headers: [
      ['content-type', 'text/html',],
      ['set-cookie', 'a=a',],
      ['set-cookie', 'b=b',],
      ['set-cookie', 'c=c',],
    ]
  };
};
```

### Returned response

```
Content-Length: 40
content-type: text/html
Date: Tue, 22 Jan 2019 01:58:28 GMT
Server: Werkzeug/0.14.1 Python/2.7.15
set-cookie: c=c

sam local start-api multiple headers bug

```

### Expected response

```
Content-Length: 40
content-type: text/html
Date: Tue, 22 Jan 2019 01:58:28 GMT
Server: Werkzeug/0.14.1 Python/2.7.15
set-cookie: a=a
set-cookie: b=b
set-cookie: c=c

sam local start-api multiple headers bug

```

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Windows 10
2. `sam--version`:
```
SAM CLI, version 0.10.0
```
3. `cat templte.yaml`':
```
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    CodeUri: build/
    Handler: server.main
    Runtime: nodejs8.10
    Timeout: 10

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
      Events:
        root:
          Type: Api
          Properties:
            Path: /
            Method: any

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"

  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn

  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
```
