### ISSUE TITLE
AutoPublishAlias does not accept a !Ref

### ISSUE THREAD

**Issue by milancermak** [awslabs/aws-sam-cli#952]
**Description:**
Using a `!Ref` in `AutoPublishAlias` throws an error when running `sam validate`.

This is a duplicate of awslabs/cfn-python-lint#582 but it looks like it's a SAM error and not a cfn-lint error, so I'm opening a ticket here.

It is _not_ a duplicate of #220 as using`!Ref` in `AutoPublishAlias` should be allowed. Even the error message say so.

**Steps to reproduce the issue:**
1. Use this template:
```yaml
---

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Stage:
    Description: Environment stage (deployment phase)
    Type: String
    AllowedValues:
      - beta
      - prod

Resources:

  SkillFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: '.'
      Handler: main.handler
      Runtime: python3.7
      Timeout: 30
      MemorySize: 128
      AutoPublishAlias: !Ref Stage

```
2. Run `sam validate` on that template

**Observed result:**
The command results in an error 💥 

`Error: [InvalidResourceException('SkillFunction', "'AutoPublishAlias' must be a string or a Ref to a template parameter")] ('SkillFunction', "'AutoPublishAlias' must be a string or a Ref to a template parameter")`

**Expected result:**
The command finishes successfully without any error message.
