### ISSUE TITLE
trigger lambda by dynamodb

### ISSUE THREAD

**Issue by AmineVolk** [awslabs/aws-sam-cli#974]
hi all,
I have a question concerning the sam cli that I use to develop and test the lambdas locally.

I've created the lamba which is supposed to start when my dynamodb changes, when I deploy in AWS console everything works fine, but the problem is that I cannot test it locally.

I want to know if there's a way to do it, if it's a yes could you tell me how can I proceed. Below is my sam template and lambda to trigger

Thank you

tempalte : 
```yaml
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >

  Sample SAM Template 

Globals:
  Function:
    Timeout: 10

Resources:
  lambdaAddUser:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdaAddUser/
      Handler: index.lambdaHandler
      FunctionName: lambdaAddUser
      Runtime: nodejs8.10
      Environment:
        Variables:
          USER_TABLE: !Ref User
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess
        - AmazonS3FullAccess
        - AWSLambdaDynamoDBExecutionRole
      Events:
        Whoami:
          Type: Api
          Properties:
            Path: /user
            Method: post

  ProcessDynamoDBStream:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ProcessDynamoDBStream/
      Handler: index.lambdaHandler
      FunctionName: ProcessDynamoDBStream
      Runtime: nodejs8.10
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess
        - AmazonS3FullAccess
        - AWSLambdaDynamoDBExecutionRole
      Events:
        Stream:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt User.StreamArn
            BatchSize: 100
            StartingPosition: TRIM_HORIZON

  User:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
```
lambda to trigger : 
```javascript
const logger = require("loggy");
const pretty = require("pretty-format");
const { sendResponse } = require("./lambdaUtile");

exports.lambdaHandler = (event, context, callback) => {
  logger.info(`*** in ProcessDynamoDBStream ***`);

  event.Records.forEach(record => {
    logger.log(`record : ${pretty(record)}`);
  });

};
sendResponse = (statusCode, message, callback) => {
  const response = {
    statusCode: statusCode,
    body: JSON.stringify(message)
  };
  callback(null, response);
};
```

whene i add item in dynamodb my lanmda is not invoked, but in aws console its work.
### Current Configuration
1. OS: mint
2. `sam --version`: SAM CLI, version 0.10.0
3. nodejs 8
